import {hasEvidence,evidenceFields,recordedModelUsage} from './recordedEvidence';
import {formatUTCDate,formatUTCTime,formatUTCDateTime} from './dateTime';
import {QueryPanel} from './HackathonWorkbench';
import {DenseTimeline} from './DenseTimeline';
import {useEffect,useState} from 'react';
import {Alert,Button,TextField,MenuItem} from '@mui/material';
import {categories,category,colors,failed,filterEvents,parseAssurance,workflowStatus,type AssuranceData} from './assuranceData';
import {exportJson} from './exportJson';
import {workshopLinks} from './workshopLinks';
const time=(v:string|number|null|undefined)=>formatUTCTime(v);
const show=(v:unknown)=>v==null?'Not recorded':typeof v==='object'?JSON.stringify(v):String(v);
function Verdict({value}:{value?:string}){const pass=value==='SATISFIED'||value==='PASS',bad=value==='NOT SATISFIED'||value==='BREACH';return <span className={`av-verdict ${pass?'pass':bad?'fail':'unknown'}`}>{pass?'✓ ':''}{value??'Not assessed'}</span>}
export function AssuranceTimeline({sharedData,selectedRun,onRun,onRefresh,sharedSource,sharedControl,onControl,sharedWindow,onWindow}:{sharedData?:AssuranceData|null;selectedRun?:string;onRun?:(id:string)=>void;onRefresh?:()=>void;sharedSource?:string;sharedControl?:string;onControl?:(c:string)=>void;sharedWindow?:number[];onWindow?:(w:number[])=>void}={}){
 const [localData,setData]=useState<AssuranceData|null>(null),[mode,setMode]=useState('Loading'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[localId,setId]=useState(''),[localControl,setLocalControl]=useState('16'),[checked,setChecked]=useState('16'),[q,setQ]=useState(''),[actor,setActor]=useState(''),[kind,setKind]=useState(''),[errorsOnly,setErrorsOnly]=useState(false),[localRange,setLocalRange]=useState<number[]>([0,100]),[bucketIds,setBucketIds]=useState<string[]>([]),[selection,setSelection]=useState(''),[auto,setAuto]=useState(false);
 const data=sharedData??localData,id=selectedRun??localId,control=sharedControl??localControl,range=sharedWindow??localRange,setControl=onControl??setLocalControl,setRange=onWindow??setLocalRange;
 async function refresh(){if(onRefresh){onRefresh();return}setBusy(true);try{const r=await fetch('api/assurance',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('Evidence service unavailable');setData(parseAssurance(await r.json()));setMode('Connected · collected evidence');setError('')}catch(e){setData(null);setMode('Evidence unavailable');setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(!onRefresh)void refresh()},[]);useEffect(()=>{if(!auto)return;const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer)},[auto]);
 const run=data?.runs.find(r=>r.id===id)??data?.runs[0];
 if(!run)return <section><p>Loading assurance evidence…</p>{error&&<Alert severity="error">{error}</Alert>}</section>;
 const usage=recordedModelUsage(run.events);
 const all=run.events,dated=all.filter(e=>e.time),times=dated.map(e=>Date.parse(e.time!)),start=times.length?Math.min(...times):0,end=times.length?Math.max(...times):1,duration=Math.max(1,end-start),window:[number,number]=[start+duration*range[0]/100,start+duration*range[1]/100];
 const visibleEvents=filterEvents(all,q,actor,kind,errorsOnly,range[0]===0&&range[1]===100?undefined:window);
 const filtered=bucketIds.length?visibleEvents.filter(e=>bucketIds.includes(e.id)):visibleEvents,chosen=filtered.find(e=>e.id===selection)??filtered[0];
 const actors=[...new Set(all.map(e=>e.actor??'Unknown'))],report=checked==='7'?run.c7:run.c16;
 const refs=run.c16['evidence.refs']??[],related=chosen?all.filter(e=>e.id!==chosen.id&&((chosen.action_id&&e.action_id===chosen.action_id)||(chosen.call_id&&e.call_id===chosen.call_id)||(chosen.logical_call_id&&(e.call_id===chosen.logical_call_id||e.logical_call_id===chosen.logical_call_id))||(chosen.invocation_id&&e.invocation_id===chosen.invocation_id))):[];
 const counts=categories.map(k=>({name:k,n:filtered.filter(e=>category(e)===k).length}));let angle=0;const gradient=counts.filter(c=>c.n).map(c=>{const from=angle;angle+=c.n/Math.max(1,filtered.length)*360;return `${colors[c.name]} ${from}deg ${angle}deg`}).join(',');
 const reset=()=>{setQ('');setActor('');setKind('');setErrorsOnly(false);setRange([0,100]);setBucketIds([])};
 function pickRun(next:string){setId(next);onRun?.(next);setSelection('');reset()}
 return <section className="av" aria-label="Assurance timeline">
 <div className="av-source"><span><b>{sharedSource??mode}</b> · {data?formatUTCDate(data.readAt):''} · Read {time(data?.readAt)} UTC{run.collectedAt&&<> · Collected {time(run.collectedAt)} UTC</>}</span><div><Button size="small" disabled={busy} onClick={refresh}>Refresh</Button><Button size="small" aria-pressed={auto} onClick={()=>setAuto(!auto)}>{auto?'Pause refresh':'Refresh every 15s'}</Button><Button size="small" onClick={()=>exportJson(`${run.id}-evidence.json`,{...data,runs:[run]})}>Export run</Button></div></div>
 {error&&<Alert severity="error">{error} · Last loaded evidence retained.</Alert>}{!!data?.errors.length&&<Alert severity="warning">{data.errors.length} runs could not be read. Their results are unavailable.</Alert>}
 <div className="av-query"><TextField size="small" select label="Control" value={control} onChange={e=>setControl(e.target.value)}><MenuItem value="7">7 · Event recording</MenuItem><MenuItem value="16">16 · Spend cap</MenuItem></TextField><TextField size="small" select label="Run" value={run.id} onChange={e=>pickRun(e.target.value)}>{data?.runs.map(r=><MenuItem value={r.id} key={r.id}>{r.id}</MenuItem>)}</TextField><Button variant="contained" onClick={()=>setChecked(control)}>View saved report</Button><span className="av-muted">Whole-run verdict · filters affect events only.</span></div>
 <div className="av-result" aria-live="polite">
 {report.verdict?<div><small>{checked==='7'?'Event recording':'Spend control'}</small><Verdict value={report.verdict}/></div>:<span className="av-muted">No saved assessment for Control {checked}. Review the evidence gaps in the independent query below.</span>}
 {evidenceFields({'Measured':checked==='7'?(report.coverage!=null?`${(report.coverage*100).toFixed(1)}% coverage`:null):(report['measured.value']!=null?`${Number(report['measured.value']).toLocaleString()} tokens`:null),'Threshold':checked==='7'?(run.c7Threshold.coverage_target!=null?`${Number(run.c7Threshold.coverage_target)*100}% coverage`:null):(report['threshold.value']!=null?`${Number(report['threshold.value']).toLocaleString()} tokens`:null),'Version':checked==='7'?report.threshold_version:report['threshold.version']}).map(([label,v])=><div key={label}><small>{label}</small><b>{show(v)}</b></div>)}
 {usage&&<div><small>Recorded model usage · {usage.calls} attempts</small><b>{usage.total.toLocaleString()} tokens</b></div>}
 </div>
 <div className="av-status">{run.c7.verdict&&<span>Control 7 <Verdict value={run.c7.verdict}/></span>}{run.c16.verdict&&<span>Control 16 <Verdict value={run.c16.verdict}/></span>}<span><b>Workflow:</b> {workflowStatus(run)}{run.workflow.failures.length>0&&` · ${run.workflow.failures.length} recorded failures`}</span>{hasEvidence(run.budget.reserved)&&<span>{run.budget.reserved.toLocaleString()} tokens reserved</span>}</div>
 <div className="av-toolbar"><TextField size="small" label="Search events or call ID" value={q} onChange={e=>{setQ(e.target.value);setBucketIds([])}}/><TextField size="small" select label="Agent / actor" value={actor} onChange={e=>{setActor(e.target.value);setBucketIds([])}}><MenuItem value="">All actors</MenuItem>{actors.map(a=><MenuItem key={a} value={a}>{a}</MenuItem>)}</TextField><TextField size="small" select label="Event type" value={kind} onChange={e=>{setKind(e.target.value);setBucketIds([])}}><MenuItem value="">All types</MenuItem>{categories.map(c=><MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField><Button aria-pressed={errorsOnly} variant={errorsOnly?'contained':'outlined'} onClick={()=>{setErrorsOnly(!errorsOnly);setBucketIds([])}}>Failures & refusals</Button><Button onClick={reset}>Clear filters</Button></div>
 {run.workflow.mode==='workflow'&&<Alert severity="info" sx={{mb:2}}>Showing {all.length} saved transport records from {run.workflow.stages?.filter(s=>s.invoked).length??0} agent stages. {all.filter(e=>e.phase==='tool-setup').length} are connection/setup requests, included under Tool. These are separate from the CloudWatch span tree. Zero authorization, budget or notification records means those records are absent from this export.</Alert>}
 <DenseTimeline events={filterEvents(all,q,actor,kind,errorsOnly)} start={start} end={end} range={range} onRange={setRange} selectedIds={bucketIds} onInspect={ids=>{setBucketIds(ids);setSelection(ids[0]??'')}}/>
 {bucketIds.length>0&&<div className="dt-selection" role="status"><b>{filtered.length} records in selected bar</b><Button size="small" onClick={()=>setBucketIds([])}>Show full window</Button></div>}
 <div className="av-panels"><section className="av-events"><header><b>Events ({filtered.length})</b><span>{all.length} source records · may reference the same action</span></header><div className="av-event-scroll">{filtered.length?filtered.map(e=><button key={e.id} className={`av-event ${chosen?.id===e.id?'selected':''}`} onClick={()=>setSelection(e.id)} aria-pressed={chosen?.id===e.id}><time>{time(e.time)}</time><span className="av-event-type" style={{color:colors[category(e)]}}>{category(e)}</span><span>{e.phase??e.outcome??'Transport attempt'}<small>{e.actor??'Unknown actor'}</small></span><span>{show(e.verdict??e.decision??e.outcome??e.delivery_status)}</span></button>):<p className="av-empty">No events match these filters. Clear filters to return to the run.</p>}</div></section>
 <section className="av-proof"><header><b>Event details</b><span>{chosen?.source??'No selection'}</span></header><div className="av-panel-scroll">{chosen?<><h3>{chosen.phase==='tool-setup'?'Connection / setup request':chosen.phase??chosen.outcome??'Recorded event'}</h3><dl>{evidenceFields({'System zone':chosen.zone,'Authority principal':chosen.principal??chosen.authority,'Accountable person':chosen.owner,'Control binding':chosen.control_id,'Actor':chosen.actor,'Time (UTC)':chosen.time?formatUTCDateTime(chosen.time):null,'Outcome':chosen.verdict??chosen.decision??chosen.outcome,'HTTP status':chosen.http_status,'Policy version':chosen.policy_version??chosen.threshold_version,'Call ID':chosen.call_id??chosen.logical_call_id,'Invocation ID':chosen.invocation_id,'Attempt ID':chosen.attempt_id,'Action ID':chosen.action_id,'Trace ID':chosen.trace_id,'Model / tool':chosen.asset?.alias??chosen.request_tool_name,...(category(chosen)==='Model'?{'Input tokens':chosen.usage?.input_tokens,'Output tokens':chosen.usage?.output_tokens}:{}),'Reason':chosen.reason??chosen.error,...(category(chosen)==='Notification'?{'Recipient':chosen.recipient,'Delivery status':chosen.delivery_status,'Delivery receipt':chosen.receipt_id}:{})}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{show(v)}</dd></div>)}</dl><details><summary>{related.length} related records · exact ID match</summary>{related.map(r=><button className="av-related" key={r.id} onClick={()=>{reset();setSelection(r.id)}}>{r.source} · {r.phase}</button>)}</details><details><summary>Inspect source record</summary><pre>{JSON.stringify(chosen,null,2)}</pre></details></>:<p className="av-empty">Select an event to inspect its proof.</p>}</div></section>
<aside className="av-summary"><header><b>Activity summary</b></header><div className="av-panel-scroll"><div className="av-donut" role="img" aria-label={counts.map(c=>`${c.name} ${c.n}`).join(', ')} style={{background:gradient?`conic-gradient(${gradient})`:'#e1e5ed'}}><div><b>{filtered.length}</b><small>records</small></div></div>{counts.map(c=><div className="av-count" key={c.name}><span><i style={{background:colors[c.name]}}/>{c.name}</span><b>{c.n}</b></div>)}<details className="summary-budget"><summary>Budget & governance</summary>{evidenceFields({'Committed tokens':run.budget.committed,'Reserved tokens':run.budget.reserved}).map(([label,v])=><p key={label}>{label}: {show(v)}</p>)}<hr/><Button size="small" component="a" href={workshopLinks.servicenow} target="_blank" rel="noopener noreferrer">ServiceNow ↗</Button><small>Browser handoff · run linkage unverified</small></details></div></aside></div>
 <QueryPanel run={run} control={control} window={range[0]===0&&range[1]===100?undefined:window}/>
 <div className="av-audit"><details ><summary>Workflow failures ({run.workflow.failures.length})</summary>{run.workflow.failures.map((f,i)=><p key={i}><b>{f.actor}</b> · {f.http_status?`HTTP ${f.http_status}`:f.outcome} · {f.request_tool_name??f.attempt_id} {f.error&&`· ${f.error}`}</p>)}{!run.workflow.failures.length&&<p>No failures in the exported runner record. This does not establish workflow completion.</p>}</details><details><summary>Gateway usage ({refs.length} references)</summary><p>Independent gateway measurements. Per-call budget-to-gateway correlation remains subject to evaluator warnings.</p>{refs.map((f:any,i:number)=><p key={i}><code>{f.call_id}</code> · {formatUTCDateTime(f.at)} UTC · {f.input_tokens} input + {f.output_tokens} output</p>)}</details><details><summary>Findings, missing evidence & source coverage</summary>{[...(run.c7.warnings??[]),...(run.c7.findings??[]),...(run.c7.uncertainties??[]),...(run.c16.warnings??[]),...(run.c16.findings??[])].map((w,i)=><p key={i}>{show(w)}</p>)}<pre>{JSON.stringify({missing:run.c7.missing_ids,unverified:run.c7.unverified_ids,sources:run.sources},null,2)}</pre><p>{data?.freshness}. Signatures and retention are not verified by this UI.</p></details></div>
 </section>
}
