import {PaginatedTable} from './PaginatedTable';
import {useState} from 'react';
import {Box,Button,Chip,Typography,TextField,MenuItem,Tooltip,Table,TableHead,TableBody,TableRow,TableCell,TableContainer} from '@mui/material';
import {controls,evaluate,rules,type Run,type Control} from './evidence';
import {traceFor} from './traceData';
import {exportJson} from './evidenceApi';
export function VerdictChip({value}:{value:string}){return <Chip size="small" label={value} sx={{fontWeight:600,color:`var(--status-${value.toLowerCase()})`,bgcolor:`var(--status-${value.toLowerCase()}-bg)`}}/>}
export function AssuranceLayer({runs,onInspect,onTrace}:{runs:Run[];onInspect:(r:Run,c:Control)=>void;onTrace:(r:Run)=>void}){
 const [id,setId]=useState('alpha-002'),[zone,setZone]=useState('Network');
 const run=runs.find(r=>r.id===id)??runs[0];if(!run)return <Typography>No runs received</Typography>;
 const trace=traceFor(run.id),spans=trace.spans.filter(s=>s.zone===zone),packets=controls.map(c=>evaluate(run,c));
 const events=run.values['7'].reduce<number>((sum,v)=>sum+(v??0),0);
 return <Box className="assurance-layer"><Box className="layer-toolbar"><div><Typography variant="overline" color="primary">ASSURANCE LAYER</Typography><Typography variant="h6">From agent action to control evidence</Typography></div><TextField select label="Run" value={run.id} onChange={e=>setId(e.target.value)} sx={{minWidth:180}}>{runs.map(r=><MenuItem key={r.id} value={r.id}>{r.id} · {r.scenario}</MenuItem>)}</TextField></Box>
 <Box className="assurance-map">{['Customer','IT','Network'].map((z,i)=>{const zs=trace.spans.filter(s=>s.zone===z),tools=zs.filter(s=>s.kind==='tool');return <Box className="zone-group" key={z}><Tooltip title={`Inspect ${z.toLowerCase()} agent, model and tool activity`}><button className={`zone-node ${zone===z?'active':''}`} onClick={()=>setZone(z)}><span className="zone-kicker">ZONE 0{i+1}</span><strong>{z} agent</strong><span>{tools.length} tool · {zs.filter(s=>s.kind==='model').length} model call</span><span className={zs.some(s=>s.status==='ERROR')?'node-error':'node-ok'}>{zs.some(s=>s.status==='ERROR')?'Tool error':'Sample trace available'}</span></button></Tooltip>{i<2&&<Tooltip title="Illustrative handoff decision. Guardrail configuration and runtime enforcement are not verified."><span className="boundary">→<small>Gate {i===0?'A':'B'}</small></span></Tooltip>}</Box>})}</Box>
 <Box className="assurance-detail"><Box className="activity-column"><Box className="layer-subheading"><Typography variant="h6">{zone} activity</Typography><Button size="small" onClick={()=>onTrace(run)}>Open trace →</Button></Box>{spans.filter(s=>s.kind!=='agent').map(s=><Box className="activity-row" key={s.id}><div><Typography variant="body2" fontWeight={600}>{s.name}</Typography><Typography variant="caption" color="text.secondary">{s.kind} · {s.duration} ms{s.tokens?` · ${s.tokens.input+s.tokens.output} tokens`:''}</Typography></div><Chip size="small" variant="outlined" label={s.status}/></Box>)}<Box className="lineage-strip"><span>Sample source</span><span>→</span><code>{trace.traceId}</code><span>→</span><span>Control records</span></Box><Typography variant="caption" color="text.secondary">Trace association by run ID; record-level span links are not captured.</Typography></Box>
 <Box className="control-column"><Typography variant="h6" mb={1}>Control evaluations</Typography>{packets.map(p=><button className="evaluation-row" key={p.controlId} onClick={()=>onInspect(run,p.controlId)}><span className="evaluation-id">C{p.controlId}</span><span><strong>{p.threshold.name}</strong><small>{p.value===null?'Measurement missing':`${Number(p.value.toFixed(1))} ${p.threshold.unit}`} · {p.threshold.version}</small></span><VerdictChip value={p.verdict}/><span>↗</span></button>)}</Box></Box>
 <Box className="assurance-bottom"><Tooltip title="Captured events / expected events from the independent sample manifest; this is not a count of trace spans."><span><strong>{events}/12</strong> events captured</span></Tooltip><span><strong>{packets.flatMap(p=>p.records).filter(r=>r.value!==null).length}/6</strong> measurements present</span><span><strong>Not recorded</strong> runtime action</span><span><strong>Not sent</strong> notification</span></Box></Box>
}
export function AuditWorkspace({runs,onInspect}:{runs:Run[];onInspect:(r:Run,c:Control)=>void}){
 const [filter,setFilter]=useState('All');const packets=runs.flatMap(run=>controls.map(control=>({run,control,packet:evaluate(run,control)})));const shown=packets.filter(p=>filter==='All'||p.packet.verdict===filter);
 return <Box className="audit-workspace"><Box className="layer-toolbar"><div><Typography variant="h6">Control evaluation ledger</Typography><Typography variant="caption" color="text.secondary">{packets.length} checks · immutable storage not connected · synthetic records</Typography></div><Box display="flex" gap={1}><TextField select label="Verdict" value={filter} onChange={e=>setFilter(e.target.value)} sx={{minWidth:130}}>{['All','Pass','Breach','Unknown'].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><Button variant="outlined" onClick={()=>exportJson('SAMPLE-audit-ledger.json',{sample:true,packets:shown.map(p=>p.packet)})}>Export {shown.length} checks</Button></Box></Box><PaginatedTable label="Control evaluation ledger" scrollClassName="wa-table-wrap"><Table aria-label="Control evaluation ledger"><TableHead><TableRow>{['Run / scenario','Control','Observed / limit','Verdict','Evidence','Action / receipt'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{shown.map(({run,control,packet:p})=><TableRow key={`${run.id}-${control}`} hover><TableCell><Button onClick={()=>onInspect(run,control)} size="small">{run.id} ↗</Button><Typography variant="caption" display="block" color="text.secondary">{run.scenario}</Typography></TableCell><TableCell>C{control} · {rules[control].name}<Typography variant="caption" display="block" color="text.secondary">{p.threshold.version}</Typography></TableCell><TableCell>{p.value===null?'—':Number(p.value.toFixed(1))} / {control==='7'?'≥':'≤'} {p.threshold.limit} {p.threshold.unit}</TableCell><TableCell><VerdictChip value={p.verdict}/></TableCell><TableCell>{p.records.filter(r=>r.value!==null).length}/{p.records.length} measurements</TableCell><TableCell><Typography variant="caption">Not performed / Not sent</Typography></TableCell></TableRow>)}</TableBody></Table></PaginatedTable></Box>
}
