import {FoundationPanel} from './FoundationPanel';
import {WorkspaceExplorer} from './WorkspaceExplorer';
import {navigationLabels} from './Sidebar';
import {parseCloudCapture,type CloudCapture} from './cloudwatchData';
import {ReadinessPanel,QueryPanel,RegisterPanel,SpendChart,OfflinePanel,ServiceNowPanel,FindingLifecycle} from './HackathonWorkbench';
import {statusClass} from './controlQuery';
import {RunTimeline,ActivityMix,ThresholdCharts,FailureChart,AuditMatrix} from './WorkspaceCharts';
import {CloudWatchTelemetry} from './CloudWatchTelemetry';
import {useEffect,useState} from 'react';
import {ThemeProvider,createTheme,CssBaseline,Button,TextField,MenuItem,IconButton,Tooltip,Alert,Drawer} from '@mui/material';
import MenuIcon from '@mui/icons-material/Menu';
import Close from '@mui/icons-material/Close';
import DarkModeOutlined from '@mui/icons-material/DarkModeOutlined';
import LightModeOutlined from '@mui/icons-material/LightModeOutlined';
import Sidebar from './Sidebar';
import {AssuranceTimeline} from './AssuranceTimeline';
import {RecentActivity} from './ScreenSummaries';
import {parseAssurance,workflowStatus,category,type AssuranceData,type AssuranceRun} from './assuranceData';
import {exportJson} from './evidenceApi';
import {workshopLinks} from './workshopEvidence';
const value=(x:any)=>x==null?'Not recorded':typeof x==='object'?JSON.stringify(x):String(x);
const number=(x:any)=>typeof x==='number'?x.toLocaleString():'Unknown';
const ok=(v:any)=>['SATISFIED','PASS'].includes(v);
function Badge({v}:{v:any}){return <span className={`wa-badge ${ok(v)?'good':['BREACH','NOT SATISFIED'].includes(v)?'bad':'unknown'}`}>{ok(v)?'✓ ':''}{v??'Not assessed'}</span>}
const captions:Record<string,string>={'Overview':'Recorded runs, control results and unresolved evidence','Agent runs':'Find a run and inspect its control and workflow outcomes','Observability':'Explore agent, model and tool records over time','Control register':'Compare measurements against versioned thresholds','Integrations':'Source availability and governance handoff','Findings & gaps':'Inspect failures and missing supporting evidence','Audit workspace':'Review and export the records behind each verdict','Measured impact':'Separate observed activity from demonstrated business impact','Trust chain':'Follow a decision from execution to evidence'};
export function AssuranceApp(){
 const [windowRunIds,setWindowRunIds]=useState<string[]|null>(null);
 const [importedCapture,setImportedCapture]=useState<CloudCapture|null>(null);
 const [page,setPage]=useState('Overview'),[collapsed,setCollapsed]=useState(true),[mobile,setMobile]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem('alpha-theme')!=='light');
 const [data,setData]=useState<AssuranceData|null>(null),[source,setSource]=useState('Loading evidence'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[polling,setPolling]=useState(false),[lastCheck,setLastCheck]=useState<string|null>(null),[connection,setConnection]=useState('Waiting'),[query,setQuery]=useState(''),[status,setStatus]=useState('All'),[selected,setSelected]=useState('c716-pass-03'),[control,setControl]=useState('16'),[range,setRange]=useState([0,100]);
 async function refresh(){setBusy(true);try{let d;try{const r=await fetch('api/assurance',{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error();d=parseAssurance(await r.json());setSource('Connected · collected evidence');setConnection('Connected evidence service')}catch{const r=await fetch('data/assurance-v2.json',{cache:'no-store'});if(!r.ok)throw Error('Evidence unavailable');d=parseAssurance(await r.json());setSource('Saved workshop snapshot');setConnection('Evidence service unavailable · snapshot fallback')}setData(d);setError('')}catch(e){setError((e as Error).message)}finally{setLastCheck(new Date().toISOString());setBusy(false)}}
 useEffect(()=>{void refresh();fetch('data/cloudwatch-capture.json').then(r=>r.json()).then(v=>setImportedCapture(parseCloudCapture(v))).catch(()=>{})},[]);
 useEffect(()=>{if(!polling)return;const timer=setInterval(()=>{if(!document.hidden)void refresh()},15000);return()=>clearInterval(timer)},[polling]);
 useEffect(()=>{document.title='Team Alpha | Trustworthy Observability'},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('alpha-theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{document.querySelector('main')?.scrollTo({top:0});setQuery('');setStatus('All');setWindowRunIds(null)},[page]);
 const theme=createTheme({palette:{mode:dark?'dark':'light',primary:{main:dark?'#8ab4f8':'#2378e8'},background:{default:dark?'#202124':'#f8faff',paper:dark?'#292a2d':'#fff'},text:{primary:dark?'#e8eaed':'#243247',secondary:dark?'#bdc1c6':'#617087'},divider:dark?'#3c4043':'#e4eaf2'},typography:{fontFamily:'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',fontSize:13,button:{textTransform:'none',fontWeight:500}},shape:{borderRadius:6},components:{MuiButton:{defaultProps:{disableElevation:true,size:'small'}},MuiTextField:{defaultProps:{size:'small'}},MuiPaper:{defaultProps:{elevation:0}},MuiInputBase:{styleOverrides:{root:{fontSize:12}}}}});
 const runs=data?.runs??[],run=runs.find(r=>r.id===selected)??runs[0];
 const shown=runs.filter(r=>(!query||`${r.id} ${r.scenario}`.toLowerCase().includes(query.toLowerCase()))&&(status==='All'||(status==='Failures'?r.workflow.failures.length>0:status==='Unknown'?statusClass(r.c7.verdict)==='unknown'||statusClass(r.c16.verdict)==='unknown':ok(r.c7.verdict)&&ok(r.c16.verdict))));
 const records=runs.reduce((n,r)=>n+r.events.length,0),failures=runs.reduce((n,r)=>n+r.workflow.failures.length,0),report=run?(control==='7'?run.c7:control==='16'?run.c16:{}):{};
 function selectRun(id:string){setSelected(id);setRange([0,100])}
 function drill(r:AssuranceRun){selectRun(r.id);setPage('Observability')}
 const workspaceScope=['Overview','Agent runs','Agents & principals','Evidence explorer','Evidence coverage','Live monitor','Foundation & runtime','Notifications & receipts','Integrations','Measured impact'].includes(page);
 const exportRun=()=>run&&exportJson(`${run.id}-evidence.json`,{...data,runs:[run]});
 const runSelector=<TextField select label="Run" value={run?.id??''} onChange={e=>selectRun(e.target.value)} className="wa-run-select">{runs.map(r=><MenuItem key={r.id} value={r.id}>{r.id}</MenuItem>)}</TextField>;
 useEffect(()=>{const visible=windowRunIds?shown.filter(r=>windowRunIds.includes(r.id)):shown;if(['Overview','Agent runs'].includes(page)&&visible.length&&!visible.some(r=>r.id===selected))setSelected(visible[0].id)},[windowRunIds,query,status,page,data]);
 const tableRuns=windowRunIds?shown.filter(r=>windowRunIds.includes(r.id)):shown;
 const runTable=<section className="wa-panel wa-runs"><header><h2>Runs</h2><span>{tableRuns.length} of {runs.length} recorded runs</span></header><div className="wa-table-wrap"><table><thead><tr><th>Run / scenario</th><th>Control 7</th><th>Control 16</th><th>Records</th><th>Workflow</th></tr></thead><tbody>{tableRuns.map(r=><tr key={r.id} className={r.id===run?.id?'selected':''}><td><button className="wa-link" onClick={()=>selectRun(r.id)}>{r.id}</button><small>{r.scenario}</small></td><td><Badge v={r.c7.verdict}/></td><td><Badge v={r.c16.verdict}/></td><td>{r.events.length}</td><td>{workflowStatus(r)}<small>{r.workflow.failures.length} recorded failures</small></td></tr>)}</tbody></table>{!tableRuns.length&&<p className="wa-empty">No matching runs. Clear the filters to see all evidence.</p>}</div><footer>Source records may refer to the same action.</footer></section>;
 const runDetail=run&&(!['Overview','Agent runs'].includes(page)||tableRuns.some(r=>r.id===run.id))&&<aside className="wa-panel wa-detail"><header><h2>Run details</h2><span>{run.id}</span></header><dl>{Object.entries({'Scenario':run.scenario,'Workflow':workflowStatus(run),'Control 7':run.c7.verdict??'Not assessed','Control 16':run.c16.verdict??'Not assessed','Collected (UTC)':run.collectedAt,'Records':run.events.length,'Committed tokens':run.budget.committed,'Reserved tokens':run.budget.reserved,'Threshold version':run.c16['threshold.version'],'Evidence authenticity':'Not independently verified'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{value(v)}</dd></div>)}</dl><div className="wa-actions"><Button variant="outlined" onClick={()=>drill(run)}>Inspect execution →</Button><Button onClick={exportRun}>Export evidence</Button></div></aside>;
 const controlsTable=run&&<section className="wa-panel"><header><h2>Control results</h2><span>Whole-run assessments</span></header><div className="wa-table-wrap"><table><thead><tr><th>Control</th><th>Verdict</th><th>Measured</th><th>Threshold</th><th>Version</th><th/></tr></thead><tbody>{['7','9','16'].map(c=>{const r=c==='7'?run.c7:c==='16'?run.c16:{};return <tr key={c}><td>{c} · {c==='7'?'Event recording':c==='9'?'Performance drift':'Spend cap'}</td><td><Badge v={r.verdict}/></td><td>{c==='7'&&r.coverage!=null?`${(r.coverage*100).toFixed(0)}% · ${r.observed_count}/${r.expected_count}`:c==='16'?number(r['measured.value'])+' tokens':'Unknown'}</td><td>{c==='7'&&run.c7Threshold.coverage_target!=null?`${run.c7Threshold.coverage_target*100}% coverage`:c==='16'?number(r['threshold.value'])+' tokens':'Not recorded'}</td><td>{value(c==='7'?r.threshold_version:r['threshold.version'])}</td><td><Button onClick={()=>setControl(c)}>Inspect</Button></td></tr>})}</tbody></table></div></section>;
 return <ThemeProvider theme={theme}><CssBaseline/><div className="wa-app"><header className="wa-appbar"><div className="wa-brand"><span className="wa-alpha-logo" role="img" aria-label="Team Alpha logo"/><b>Team Alpha</b><em>Observability</em></div><div className="wa-header-actions"><Tooltip title={dark?'Light appearance':'Dark appearance'}><IconButton aria-label={dark?'Light appearance':'Dark appearance'} onClick={()=>setDark(!dark)}>{dark?<LightModeOutlined/>:<DarkModeOutlined/>}</IconButton></Tooltip><span className="wa-avatar" aria-label="Workspace member">AD</span></div></header><div className={`wa-layout ${collapsed?'wa-collapsed':''}`}><div className="wa-navigation"><IconButton aria-label={collapsed?'Expand navigation':'Collapse navigation'} onClick={()=>setCollapsed(!collapsed)}><MenuIcon/></IconButton><Sidebar id="workspace-navigation" page={page} collapsed={collapsed} onNavigate={setPage}/></div><Drawer open={mobile} onClose={()=>setMobile(false)}><Sidebar id="mobile-navigation" page={page} onNavigate={p=>{setPage(p);setMobile(false)}}/></Drawer><main className="wa-main"><header className="wa-pagebar"><IconButton className="wa-mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><MenuIcon/></IconButton><div><h1>{navigationLabels[page]??page}</h1><p>{captions[page]??({'Agents & principals':'Observed agents, tools and service identities across all runs','Evidence explorer':'Search and correlate actions, decisions and outcomes across the workspace','Evidence coverage':'Source completeness and evidence fields across every collected run','Foundation & runtime':'Fresh AWS preflight, deployment configuration and platform evidence access','Live monitor':'Monitor collected execution evidence and connection freshness','Notifications & receipts':'Inspect queued notices, recipients and recorded delivery outcomes across runs'} as Record<string,string>)[page]}</p></div>{page!=='Trust chain'&&<div className="wa-page-actions"><Button variant="outlined" disabled={busy} onClick={refresh}>Refresh</Button><Button variant="outlined" disabled={!data} onClick={()=>workspaceScope?exportJson('alpha-workspace-evidence.json',data):exportRun()}>{workspaceScope?'Export workspace':'Export run'}</Button></div>}</header>
 {page==='Trust chain'?<AssuranceTimeline sharedData={data} selectedRun={selected} onRun={selectRun} onRefresh={refresh} sharedSource={source} sharedControl={control} onControl={setControl} sharedWindow={range} onWindow={setRange}/>:<><div className="wa-source"><b>{source}</b><span>Read {data?new Date(data.readAt).toLocaleString('en-GB',{timeZone:'UTC'}):'—'} UTC</span><span>Control 9: not assessed in workshop evidence</span></div>{error&&<Alert severity="error">{error}. Last loaded records retained.</Alert>}{!!data?.errors.length&&<Alert severity="warning">{data.errors.length} runs could not be loaded.</Alert>}
 {page==='Foundation & runtime'&&<FoundationPanel/>}
 {data&&['Agents & principals','Evidence explorer','Evidence coverage','Notifications & receipts'].includes(page)&&<WorkspaceExplorer key={page} data={data} mode={page==='Agents & principals'?'agents':page==='Evidence coverage'?'coverage':page==='Notifications & receipts'?'notifications':'events'} onRun={id=>{selectRun(id);setPage('Trust chain')}}/>}
 {page==='Live monitor'&&<><section className="wa-panel"><header><h2>Execution evidence monitor</h2><span>{connection}</span><Button variant={polling?'contained':'outlined'} onClick={()=>setPolling(!polling)}>{polling?'Pause monitoring':'Monitor every 15s'}</Button></header><div className="hx-result"><span>Last connection check <b>{lastCheck??'Waiting'}</b></span><span>Evidence read at <b>{data?.readAt??'Waiting'}</b></span><span>Runs <b>{runs.length}</b></span><span>Source records <b>{records.toLocaleString()}</b></span></div><p>Refresh reads collected runtime outputs. A snapshot fallback is never labelled live. Monitoring pauses when the browser tab is hidden.</p><p>Starting an AWS execution requires the deployed runner; this read-only evidence service does not launch agents.</p><Button component="a" href={workshopLinks.ide} target="_blank" rel="noopener noreferrer">Open deployed runner ↗</Button></section><RecentActivity runs={runs} onInspect={id=>{selectRun(id);setPage('Trust chain')}}/></>}
 {['Overview','Agent runs'].includes(page)&&<><div className="wa-toolbar"><TextField label="Search runs" placeholder="Run ID or scenario" value={query} onChange={e=>setQuery(e.target.value)}/><TextField select label="Status" value={status} onChange={e=>setStatus(e.target.value)}>{['All','Satisfied','Failures','Unknown'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><Button onClick={()=>{setQuery('');setStatus('All');setWindowRunIds(null)}}>Clear filters</Button></div>{page==='Overview'&&<>{data&&<ReadinessPanel data={data} onRun={id=>{selectRun(id);setPage('Audit workspace')}}/>}<div className="wa-statstrip">{[['Recorded runs',runs.length],['Source records',records.toLocaleString()],['C7 + C16 satisfied',runs.filter(r=>ok(r.c7.verdict)&&ok(r.c16.verdict)).length],['Workflow failures',failures]].map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div></>}{page==='Agent runs'&&<RunTimeline onWindowIds={setWindowRunIds} runs={shown} selected={run?.id} onSelect={selectRun}/>}<div className="wa-split">{page==='Overview'?<ActivityMix runs={shown}/>:runTable}{runDetail}</div></>}
 {page==='Observability'&&run&&<><div className="wa-toolbar">{runSelector}<Button variant="outlined" onClick={()=>setPage('Trust chain')}>Inspect run events →</Button></div><CloudWatchTelemetry run={run} sharedCapture={importedCapture}/></>}
 {['Control register','Audit workspace'].includes(page)&&run&&<><div className="wa-toolbar">{runSelector}<TextField select label="Control" value={control} onChange={e=>setControl(e.target.value)}>{['7','9','16'].map(c=><MenuItem key={c} value={c}>Control {c}</MenuItem>)}</TextField><Button variant="outlined" onClick={()=>exportJson(`${run.id}-control-${control}.json`,{runId:run.id,source,control,report})}>Export control</Button>{page==='Audit workspace'&&<Button variant="outlined" onClick={()=>exportJson('workshop-evaluation-ledger.json',{source,readAt:data?.readAt,evaluations:runs.map(r=>({runId:r.id,collectedAt:r.collectedAt,control7:r.c7,control16:r.c16,workflow:workflowStatus(r)}))})}>Export all evaluations</Button>}</div><RegisterPanel run={run} control={control}/><QueryPanel run={run} control={control}/>{page==='Audit workspace'&&data&&<OfflinePanel data={data} telemetry={importedCapture} onImport={(d,c)=>{setPolling(false);setImportedCapture(c??null);setData(d);setSource('Imported offline audit bundle');selectRun(d.runs[0]?.id??'');setWindowRunIds(null)}}/>}{page==='Control register'?<><ThresholdCharts run={run}/><SpendChart run={run}/></>:<AuditMatrix runs={runs} onSelect={selectRun}/>}<div style={{marginTop:16}}>{controlsTable}</div><div className="wa-split"><section className="wa-panel"><header><h2>Control {control} · Supporting evidence</h2><Badge v={report.verdict}/></header><div className="wa-evidence-body">{control==='9'?<p>No workshop evaluation for Control 9. A verdict cannot be established.</p>:<><dl className="wa-facts">{Object.entries(control==='7'?{'Expected events':run.c7.expected_count,'Observed events':run.c7.observed_count,'Threshold version':run.c7.threshold_version,'Missing IDs':run.c7.missing_ids}:{'Measured tokens':run.c16['measured.value'],'Threshold tokens':run.c16['threshold.value'],'Threshold version':run.c16['threshold.version'],'Reserved tokens':run.budget.reserved}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{value(v)}</dd></div>)}</dl><details><summary>Evaluator report</summary><pre>{JSON.stringify(report,null,2)}</pre></details>{[...(report.warnings??[]),...(report.findings??[])].map((f:any,i:number)=><p key={i}>{value(f)}</p>)}</>}</div></section>{runDetail}</div></>}
 {page==='Findings & gaps'&&run&&<><div className="wa-toolbar">{runSelector}<TextField label="Search failures and gaps" value={query} onChange={e=>setQuery(e.target.value)}/></div><FindingLifecycle run={run}/><FailureChart run={run}/><div className="wa-split"><section className="wa-panel"><header><h2>Workflow failures</h2><span>{run.workflow.failures.length} recorded</span></header><div className="wa-table-wrap"><table><thead><tr><th>Actor</th><th>Failure</th><th>Evidence reference</th></tr></thead><tbody>{run.workflow.failures.filter(f=>JSON.stringify(f).toLowerCase().includes(query.toLowerCase())).map((f,i)=><tr key={i}><td>{f.actor??'Unknown'}</td><td><span className="wa-badge bad">{f.http_status?`HTTP ${f.http_status}`:f.outcome??'Failure'}</span><small>{f.error}</small></td><td>{f.request_tool_name??f.attempt_id??'Not recorded'}</td></tr>)}</tbody></table>{!run.workflow.failures.length&&<p className="wa-empty">No failures in this export. Workflow completion remains a separate assessment.</p>}</div></section><aside className="wa-panel wa-detail"><header><h2>Evidence gaps</h2><span>Open / unverified</span></header><div className="wa-evidence-body">{[...(run.c7.warnings??[]),...(run.c7.findings??[]),...(run.c7.uncertainties??[]),...(run.c16.warnings??[]),...(run.c16.findings??[])].filter(f=>value(f).toLowerCase().includes(query.toLowerCase())).map((f,i)=><p key={i}>{value(f)}</p>)}<p>Evidence signature and retention not verified.</p><p>ServiceNow run linkage and notification receipt not established.</p><Button variant="outlined" onClick={()=>drill(run)}>Investigate execution →</Button></div></aside></div></>}
 {page==='Integrations'&&<><ServiceNowPanel/><section className="wa-panel wa-sources"><header><h2>Sources & governance</h2><span>Last observed status · no automatic sync claim</span></header><div className="wa-table-wrap"><table><thead><tr><th>Source</th><th>Access / data</th><th>Evidence status</th><th>Next action</th></tr></thead><tbody>{[['AWS workshop',source,`${runs.length} run exports available`,workshopLinks.workshop,'Open workshop'],['Assurance evidence service','Same-origin read-only endpoint',source.startsWith('Connected')?'Responding with collected evidence':'Snapshot fallback in use',workshopLinks.ide,'Open IDE'],['CloudWatch / OTEL','Browser-captured telemetry',importedCapture?`${importedCapture.spans.length} spans · captured ${importedCapture.capturedAt} · ${importedCapture.coverage}`:'Capture not loaded','https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1','Open CloudWatch'],['ServiceNow Control Tower','Browser workflow','Per-run linkage unverified',workshopLinks.servicenow,'Open Control Tower'],['AI Agent Studio','Browser workflow','Notification delivery unverified',workshopLinks.studio,'Open Agent Studio']].map(([name,access,state,url,label])=><tr key={name}><td data-label="Source"><b>{name}</b></td><td data-label="Access / data">{access}</td><td data-label="Evidence status"><span className="wa-source-status">{state}</span></td><td data-label="Next action"><Button component="a" href={url} target="_blank" rel="noopener noreferrer">{label} ↗</Button></td></tr>)}</tbody></table></div><footer>Opening ServiceNow does not create a finding or send a notification.</footer></section></>}
 {page==='Measured impact'&&<><div className="wa-statstrip">{[['Observed runs',runs.length],['Model records',runs.reduce((n,r)=>n+r.events.filter(e=>category(e)==='Model').length,0)],['Recorded failures',failures],['Verified business benefit','Not measured']].map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><section className="wa-panel"><header><h2>Business impact</h2><span>Baseline evidence required</span></header><div className="wa-table-wrap"><table><thead><tr><th>Measure</th><th>Result</th><th>Evidence needed</th></tr></thead><tbody>{[['Investigation time saved','Matched investigation timings before and after'],['Prevented overspend','Rejected requests, deduplicated usage and model pricing'],['Resolution improvement','Matched cases, verified resolution outcomes and baseline'],['Notification delivery rate','Breach IDs, recipients and delivery receipts']].map(([name,need])=><tr key={name}><td>{name}</td><td><Badge v="Not measured"/></td><td>{need}</td></tr>)}</tbody></table></div><footer>Control satisfaction does not establish workflow completion or business benefit.</footer></section></>}
 </>}<footer className="wa-footer">TEAM ALPHA · TRUSTWORTHY OBSERVABILITY · Evidence scope and verification remain visible</footer></main></div></div></ThemeProvider>
}
