import {formatUTCDateTime} from './dateTime';
import {BrandLogo} from './BrandLogo';
import {SupportingEvidence} from './SupportingEvidence';
import {assessmentLabel} from './recordedEvidence';
import {MetricCard,type MetricIcon} from './MetricCard';
import {PaginatedTable} from './PaginatedTable';
import {ExecutionMonitor} from './ExecutionMonitor';
import {ExecutionPanel} from './ExecutionPanel';
import {createWorkspaceTheme} from './workspaceTheme';
import {WorkspaceExplorer} from './WorkspaceExplorer';
import {navigationLabels, navigationSection} from './Sidebar';
import PageHeader from './PageHeader';
import ChevronLeft from '@mui/icons-material/ChevronLeft';
import type {CloudCapture} from './cloudwatchData';
import {ReadinessPanel,QueryPanel,RegisterPanel,SpendChart,OfflinePanel,ServiceNowPanel,FindingLifecycle,JudgeControlSummary} from './HackathonWorkbench';
import {statusClass} from './controlQuery';
import {RunTimeline,ActivityMix,ThresholdCharts,FailureChart,AuditMatrix} from './WorkspaceCharts';
import {CloudWatchTelemetry} from './CloudWatchTelemetry';
import {useEffect,useState} from 'react';
import {ThemeProvider,CssBaseline,Button,TextField,MenuItem,IconButton,Tooltip,Alert,Drawer} from '@mui/material';
import DarkModeOutlined from '@mui/icons-material/DarkModeOutlined';
import LightModeOutlined from '@mui/icons-material/LightModeOutlined';
import Sidebar from './Sidebar';
import {AssuranceTimeline} from './AssuranceTimeline';
import {RecentActivity} from './ScreenSummaries';
import {JudgeJourney} from './JudgeJourney';
import {parseAssurance,workflowStatus,category,type AssuranceData,type AssuranceRun} from './assuranceData';
import {exportJson} from './exportJson';
import {workshopLinks} from './workshopLinks';
const value=(x:any)=>x==null?'Not recorded':typeof x==='object'?JSON.stringify(x):String(x);
const number=(x:any)=>typeof x==='number'?x.toLocaleString():'Unknown';
const ok=(v:any)=>['SATISFIED','PASS'].includes(v);
function Badge({v}:{v:any}){return <span className={`wa-badge ${ok(v)?'good':['BREACH','NOT SATISFIED'].includes(v)?'bad':'unknown'}`}>{ok(v)?'✓ ':''}{v??'Not assessed'}</span>}
const captions:Record<string,string>={'Journey':'Launch one scenario and follow it from customer request to trace, controls and outcome','Overview':'Recorded runs, control results and unresolved evidence','Agent runs':'Find a run and inspect its control and workflow outcomes','Observability':'Explore agent, model and tool records over time','Control register':'Compare measurements against versioned thresholds','Integrations':'Source availability and governance handoff','Findings & gaps':'Inspect failures and missing supporting evidence','Audit workspace':'Review and export the records behind each verdict','Measured impact':'Separate observed activity from demonstrated business impact','Trust chain':'Follow a decision from execution to evidence'};
export function AssuranceApp(){
 const [windowRunIds,setWindowRunIds]=useState<string[]|null>(null);
 const [importedCapture,setImportedCapture]=useState<CloudCapture|null>(null);
 const [liveCapture,setLiveCapture]=useState<CloudCapture|null>(null);
 const [page,setActivePage]=useState('Journey'),[collapsed,setCollapsed]=useState(()=>localStorage.getItem('alpha-sidebar')==='collapsed'),[mobile,setMobile]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem('alpha-theme')!=='light');
 const setPage=(next:string)=>setActivePage(next==='Foundation & runtime'?'Journey':next==='Observability'?'Trust chain':next);
 const [data,setData]=useState<AssuranceData|null>(null),[source,setSource]=useState('Loading evidence'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[polling,setPolling]=useState(false),[lastCheck,setLastCheck]=useState<string|null>(null),[connection,setConnection]=useState('Waiting'),[query,setQuery]=useState(''),[status,setStatus]=useState('All'),[selected,setSelected]=useState(''),[control,setControl]=useState('16'),[range,setRange]=useState([0,100]);
 async function refresh(){setBusy(true);setImportedCapture(null);setLiveCapture(null);try{const r=await fetch('api/assurance',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error(`Evidence service unavailable (HTTP ${r.status})`);const d=parseAssurance(await r.json());setData(d);setSource('Connected · collected evidence');setConnection('Connected evidence service');setError('')}catch(e){setData(null);setSource('Evidence unavailable');setConnection('Evidence service disconnected');setError((e as Error).message)}finally{setLastCheck(new Date().toISOString());setBusy(false)}}
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{if(!polling)return;const timer=setInterval(()=>{if(!document.hidden)void refresh()},15000);return()=>clearInterval(timer)},[polling]);
 useEffect(()=>{localStorage.setItem('alpha-sidebar',collapsed?'collapsed':'expanded')},[collapsed]);
 useEffect(()=>{document.title='Team Alpha | Trustworthy Observability'},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('alpha-theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{document.querySelector('main')?.scrollTo({top:0});setQuery('');setStatus('All');setWindowRunIds(null)},[page]);
 const theme=createWorkspaceTheme(dark);
 const runs=data?.runs??[],run=runs.find(r=>r.id===selected)??runs[0];
 const shown=runs.filter(r=>(!query||`${r.id} ${r.scenario}`.toLowerCase().includes(query.toLowerCase()))&&(status==='All'||(status==='Failures'?r.workflow.failures.length>0:status==='Unknown'?statusClass(r.c7.verdict)==='unknown'||statusClass(r.c16.verdict)==='unknown':ok(r.c7.verdict)&&ok(r.c16.verdict))));
 const records=runs.reduce((n,r)=>n+r.events.length,0),failures=runs.reduce((n,r)=>n+r.workflow.failures.length,0),report=run?(control==='7'?run.c7:control==='16'?run.c16:run.c9??{}):{};
 function selectRun(id:string){setSelected(id);setRange([0,100])}
 function drill(r:AssuranceRun){selectRun(r.id);setPage('Observability')}
 const workspaceScope=['Journey','Overview','Agent runs','Agents & principals','Evidence explorer','Evidence coverage','Live monitor','Notifications & receipts','Integrations','Measured impact'].includes(page);
 const exportRun=()=>run&&exportJson(`${run.id}-evidence.json`,{...data,runs:[run]});
 const runSelector=<TextField select label="Run" value={run?.id??''} onChange={e=>selectRun(e.target.value)} className="wa-run-select">{runs.map(r=><MenuItem key={r.id} value={r.id}>{r.id}</MenuItem>)}</TextField>;
 useEffect(()=>{const visible=windowRunIds?shown.filter(r=>windowRunIds.includes(r.id)):shown;if(['Overview','Agent runs'].includes(page)&&visible.length&&!visible.some(r=>r.id===selected))setSelected(visible[0].id)},[windowRunIds,query,status,page,data]);
 const tableRuns=windowRunIds?shown.filter(r=>windowRunIds.includes(r.id)):shown;
 const runTable=<section className="wa-panel wa-runs"><header><h2>Runs</h2><span>{tableRuns.length} of {runs.length} recorded runs</span></header><PaginatedTable label="Runs" scrollClassName="wa-table-wrap"><table><thead><tr><th>Run / scenario</th><th>Control 7</th><th>Control 16</th><th>Records</th><th>Workflow</th></tr></thead><tbody>{tableRuns.map(r=><tr key={r.id} className={r.id===run?.id?'selected':''}><td><button className="wa-link" onClick={()=>selectRun(r.id)}>{r.id}</button><small>{r.scenario}</small></td><td><Badge v={r.c7.verdict}/></td><td><Badge v={r.c16.verdict}/></td><td>{r.events.length}</td><td>{workflowStatus(r)}<small>{r.workflow.failures.length} recorded failures</small></td></tr>)}</tbody></table>{!tableRuns.length&&<p className="wa-empty">No matching runs. Clear the filters to see all evidence.</p>}</PaginatedTable><footer>Source records may refer to the same action.</footer></section>;
 const runDetail=run&&(!['Overview','Agent runs'].includes(page)||tableRuns.some(r=>r.id===run.id))&&<aside className="wa-panel wa-detail wa-run-detail"><header><h2>Run details</h2><span>{run.id}</span></header><dl>{Object.entries({'Scenario':run.scenario,'Workflow':workflowStatus(run),'Control 7':run.c7.verdict??'Not assessed','Control 16':run.c16.verdict??'Not assessed','Collected (UTC)':formatUTCDateTime(run.collectedAt),'Records':run.events.length,'Committed tokens':run.budget.committed,'Reserved tokens':run.budget.reserved,'Threshold version':run.c16['threshold.version'],'Evidence authenticity':'Not independently verified'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{value(v)}</dd></div>)}</dl><div className="wa-actions"><Button variant="outlined" onClick={()=>drill(run)}>Inspect execution →</Button><Button onClick={exportRun}>Export evidence</Button></div></aside>;
 const controlsTable=run&&<section className="wa-panel"><header><h2>Control assessment status</h2><span>Recorded results and assessment readiness</span></header><PaginatedTable label="Control results" scrollClassName="wa-table-wrap" resetKey={run.id}><table><thead><tr><th>Control</th><th>Verdict</th><th>Measured</th><th>Threshold</th><th>Version</th><th/></tr></thead><tbody>{['7','9','16'].map(c=>{const r=c==='7'?run.c7:c==='16'?run.c16:run.c9??{};return <tr key={c}><td>{c} · {c==='7'?'Event recording':c==='9'?'Performance drift':'Spend cap'}</td><td><span className={`wa-badge ${statusClass(r.verdict)}`}>{assessmentLabel(r)}</span></td><td>{c==='7'&&r.coverage!=null?`${(r.coverage*100).toFixed(0)}% · ${r.observed_count}/${r.expected_count}`:c==='16'?number(r['measured.value'])+' tokens':number(r['measured.value'])}</td><td>{c==='7'&&run.c7Threshold.coverage_target!=null?`${run.c7Threshold.coverage_target*100}% coverage`:c==='16'?number(r['threshold.value'])+' tokens':number(r['threshold.value'])}</td><td>{value(c==='7'?r.threshold_version:r['threshold.version'])}</td><td><Button onClick={()=>setControl(c)}>Inspect</Button></td></tr>})}</tbody></table></PaginatedTable></section>;
 return <ThemeProvider theme={theme}><CssBaseline/><div className="wa-app"><header className="wa-appbar"><div className="wa-brand"><BrandLogo/><div className="wa-brand-copy"><b>Team Alpha</b><span>Trustworthy observability</span></div></div><div className="wa-header-actions">{page==='Journey'&&<Button className="chat-workspace-menu" onClick={()=>setMobile(true)}>Workspace</Button>}<Tooltip title={dark?'Light appearance':'Dark appearance'}><IconButton aria-label={dark?'Light appearance':'Dark appearance'} onClick={()=>setDark(!dark)}>{dark?<LightModeOutlined/>:<DarkModeOutlined/>}</IconButton></Tooltip><span className="wa-avatar" aria-label="Workspace member">AD</span></div></header><div className={`wa-layout ${collapsed?'wa-collapsed':''}`}><div className="wa-navigation"><div className="wa-navigation-heading"><div className="wa-navigation-title" aria-hidden={collapsed}><strong>Alpha workspace</strong><span>Evidence & assurance</span></div><Tooltip title={collapsed?'Expand navigation':'Collapse navigation'} placement="right"><IconButton aria-label={collapsed?'Expand navigation':'Collapse navigation'} aria-expanded={!collapsed} aria-controls="workspace-navigation" onClick={()=>setCollapsed(!collapsed)}><ChevronLeft/></IconButton></Tooltip></div><Sidebar id="workspace-navigation" page={page} collapsed={collapsed} onNavigate={setPage}/></div><Drawer open={mobile} onClose={()=>setMobile(false)}><Sidebar id="mobile-navigation" page={page} onNavigate={p=>{setPage(p);setMobile(false)}}/></Drawer><main className="wa-main"><PageHeader section={navigationSection(page)} title={navigationLabels[page]??page} description={captions[page]??({'Agents & principals':'Observed agents, tools and service identities across all runs','Evidence explorer':'Search and correlate actions, decisions and outcomes across the workspace','Evidence coverage':'Source completeness and evidence fields across every collected run','Live monitor':'Monitor collected execution evidence and connection freshness','Notifications & receipts':'Inspect queued notices, recipients and recorded delivery outcomes across runs'} as Record<string,string>)[page]} source={source} readAt={data?.readAt} busy={busy} canExport={!!data} workspaceScope={workspaceScope} onRefresh={refresh} onExport={()=>workspaceScope?exportJson('alpha-workspace-evidence.json',data):exportRun()} onOpenNavigation={()=>setMobile(true)}/>

 {page==='Trust chain'?<AssuranceTimeline sharedData={data} selectedRun={selected} onRun={selectRun} onRefresh={refresh} sharedSource={source} sharedControl={control} onControl={setControl} sharedWindow={range} onWindow={setRange}/>:<>{error&&<Alert severity="error">{error}. Last loaded records retained.</Alert>}{!!data?.errors.length&&<Alert severity="warning">{data.errors.length} runs could not be loaded.</Alert>}
 {page==='Journey'&&<JudgeJourney data={data} onRefresh={refresh} onOpenRun={id=>{selectRun(id);setPage('Trust chain')}} onOpenControls={id=>{selectRun(id);setPage('Control register')}} onOpenTelemetry={id=>{selectRun(id);setPage('Observability')}}/>}
 {data&&['Agents & principals','Evidence explorer','Evidence coverage','Notifications & receipts'].includes(page)&&<WorkspaceExplorer key={page} data={data} mode={page==='Agents & principals'?'agents':page==='Evidence coverage'?'coverage':page==='Notifications & receipts'?'notifications':'events'} onRun={id=>{selectRun(id);setPage('Trust chain')}}/>}
 {page==='Live monitor'&&<><ExecutionPanel onRefresh={refresh} onInspect={id=>{selectRun(id);setPage('Trust chain')}}/><ExecutionMonitor connection={connection} polling={polling} lastCheck={lastCheck} readAt={data?.readAt} runs={runs.length} records={records} onToggle={()=>setPolling(!polling)} runnerUrl={workshopLinks.ide}/><RecentActivity runs={runs} onInspect={id=>{selectRun(id);setPage('Trust chain')}}/></>}
 {['Overview','Agent runs'].includes(page)&&<>{page==='Overview'&&<div className="wa-statstrip">{[['Recorded runs',runs.length],['Source records',records.toLocaleString()],['C7 + C16 satisfied',runs.filter(r=>ok(r.c7.verdict)&&ok(r.c16.verdict)).length],['Workflow failures',failures]].map(([k,v],i)=><MetricCard key={k} label={String(k)} value={v} icon={(['runs','records','verified','failures'] as MetricIcon[])[i]}/>)}</div>}<div className="wa-toolbar"><TextField label="Search runs" placeholder="Run ID or scenario" value={query} onChange={e=>setQuery(e.target.value)}/><TextField select label="Status" value={status} onChange={e=>setStatus(e.target.value)}>{['All','Satisfied','Failures','Unknown'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><Button onClick={()=>{setQuery('');setStatus('All');setWindowRunIds(null)}}>Clear filters</Button></div>{page==='Overview'&&<>{data&&<ReadinessPanel data={data} onRun={id=>{selectRun(id);setPage('Audit workspace')}}/>}</>}{page==='Agent runs'&&<RunTimeline onWindowIds={setWindowRunIds} runs={shown} selected={run?.id} onSelect={selectRun}/>}<div className="wa-split wa-summary-split">{page==='Overview'?<ActivityMix runs={shown}/>:runTable}{runDetail}</div></>}
 {page==='Observability'&&run&&<><div className="wa-toolbar">{runSelector}<Button variant="outlined" onClick={()=>setPage('Trust chain')}>Inspect run events →</Button></div><CloudWatchTelemetry run={run} sharedCapture={importedCapture} onCapture={setLiveCapture}/></>}
 {['Control register','Audit workspace'].includes(page)&&run&&<><div className="wa-toolbar">{runSelector}<TextField select label="Control" value={control} onChange={e=>setControl(e.target.value)}>{['7','9','16'].map(c=><MenuItem key={c} value={c}>Control {c}</MenuItem>)}</TextField><Button variant="outlined" onClick={()=>exportJson(`${run.id}-control-${control}.json`,{runId:run.id,source,control,report})}>Export control</Button>{page==='Audit workspace'&&<Button variant="outlined" onClick={()=>exportJson('workshop-evaluation-ledger.json',{source,readAt:data?.readAt,evaluations:runs.map(r=>({runId:r.id,collectedAt:r.collectedAt,control7:r.c7,control16:r.c16,workflow:workflowStatus(r)}))})}>Export all evaluations</Button>}</div><JudgeControlSummary run={run}/><RegisterPanel run={run} control={control}/><QueryPanel run={run} control={control}/>{page==='Audit workspace'&&data&&<OfflinePanel data={data} telemetry={source==='Imported offline audit bundle'?importedCapture:liveCapture} onImport={(d,c)=>{setPolling(false);setLiveCapture(null);setImportedCapture(c??null);setData(d);setSource('Imported offline audit bundle');setConnection('Offline audit bundle');setError('');selectRun(d.runs[0]?.id??'');setWindowRunIds(null)}}/>}{page==='Control register'?<><ThresholdCharts run={run}/><SpendChart run={run}/></>:<AuditMatrix runs={runs} onSelect={selectRun}/>}<div style={{marginTop:16}}>{controlsTable}</div><div className="wa-split wa-supporting-split"><SupportingEvidence run={run} control={control}/>{runDetail}</div></>}
 {page==='Findings & gaps'&&run&&<><div className="wa-toolbar">{runSelector}<TextField label="Search failures and gaps" value={query} onChange={e=>setQuery(e.target.value)}/></div><FindingLifecycle run={run}/><FailureChart run={run}/><div className="wa-split wa-findings-split"><section className="wa-panel"><header><h2>Workflow failures</h2><span>{run.workflow.failures.length} recorded</span></header><PaginatedTable label="Workflow failures" scrollClassName="wa-table-wrap" resetKey={run.id}><table><thead><tr><th>Actor</th><th>Failure</th><th>Evidence reference</th></tr></thead><tbody>{run.workflow.failures.filter(f=>JSON.stringify(f).toLowerCase().includes(query.toLowerCase())).map((f,i)=><tr key={i}><td>{f.actor??'Unknown'}</td><td><span className="wa-badge bad">{f.http_status?`HTTP ${f.http_status}`:f.outcome??'Failure'}</span><small>{f.error}</small></td><td>{f.request_tool_name??f.attempt_id??'Not recorded'}</td></tr>)}</tbody></table>{!run.workflow.failures.length&&<p className="wa-empty">No failures in this export. Workflow completion remains a separate assessment.</p>}</PaginatedTable></section><aside className="wa-panel wa-detail"><header><h2>Evidence gaps</h2><span>Open / unverified</span></header><div className="wa-evidence-body wa-gap-list">{[...(run.c7.warnings??[]),...(run.c7.findings??[]),...(run.c7.uncertainties??[]),...(run.c16.warnings??[]),...(run.c16.findings??[])].filter(f=>value(f).toLowerCase().includes(query.toLowerCase())).map((f,i)=><p key={i}>{value(f)}</p>)}<p>Evidence signature and retention not verified.</p><p>ServiceNow run linkage and notification receipt not established.</p><Button variant="outlined" onClick={()=>drill(run)}>Investigate execution →</Button></div></aside></div></>}
 {page==='Integrations'&&<><ServiceNowPanel/><section className="wa-panel wa-sources"><header><h2>Sources & governance</h2><span>Last observed status · no automatic sync claim</span></header><PaginatedTable label="Sources & governance" scrollClassName="wa-table-wrap"><table><thead><tr><th>Source</th><th>Access / data</th><th>Evidence status</th><th>Next action</th></tr></thead><tbody>{[['AWS workshop',source,`${runs.length} run exports available`,workshopLinks.workshop,'Open workshop'],['Assurance evidence service','Same-origin read-only endpoint',source.startsWith('Connected')?'Responding with collected evidence':'Evidence service unavailable',workshopLinks.ide,'Open IDE'],['CloudWatch / OTEL','Live time-window retrieval',importedCapture?'Imported audit-bundle telemetry available':'Open Observability to query the deployed telemetry service','https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1','Open CloudWatch'],['ServiceNow Control Tower','Browser workflow','Per-run linkage unverified',workshopLinks.servicenow,'Open Control Tower'],['AI Agent Studio','Browser workflow','Notification delivery unverified',workshopLinks.studio,'Open Agent Studio']].map(([name,access,state,url,label])=><tr key={name}><td data-label="Source"><b>{name}</b></td><td data-label="Access / data">{access}</td><td data-label="Evidence status"><span className="wa-source-status">{state}</span></td><td data-label="Next action"><Button component="a" href={url} target="_blank" rel="noopener noreferrer">{label} ↗</Button></td></tr>)}</tbody></table></PaginatedTable><footer>Opening ServiceNow does not create a finding or send a notification.</footer></section></>}
 {page==='Measured impact'&&<><div className="wa-statstrip">{[['Observed runs',runs.length],['Model records',runs.reduce((n,r)=>n+r.events.filter(e=>category(e)==='Model').length,0)],['Recorded failures',failures],['Verified business benefit','Not measured']].map(([k,v],i)=><MetricCard key={k} label={String(k)} value={v} icon={(['runs','model','failures','impact'] as MetricIcon[])[i]}/>)}</div><section className="wa-panel"><header><h2>Business impact</h2><span>Baseline evidence required</span></header><PaginatedTable label="Business impact" scrollClassName="wa-table-wrap"><table><thead><tr><th>Measure</th><th>Result</th><th>Evidence needed</th></tr></thead><tbody>{[['Investigation time saved','Matched investigation timings before and after'],['Prevented overspend','Rejected requests, deduplicated usage and model pricing'],['Resolution improvement','Matched cases, verified resolution outcomes and baseline'],['Notification delivery rate','Breach IDs, recipients and delivery receipts']].map(([name,need])=><tr key={name}><td>{name}</td><td><Badge v="Not measured"/></td><td>{need}</td></tr>)}</tbody></table></PaginatedTable><footer>Control satisfaction does not establish workflow completion or business benefit.</footer></section></>}
 </>}<footer className="wa-footer"><span>Team Alpha · Trustworthy Observability</span><span>Evidence scope and verification remain visible</span></footer></main></div></div></ThemeProvider>
}
