import {MetricCard} from './MetricCard';
import {PaginatedTable} from './PaginatedTable';
import {useEffect,useState} from 'react';
import {Alert,Button,TextField,MenuItem} from '@mui/material';
import {SpanWaterfall,MetricLine} from './WorkspaceCharts';
import {parseCloudCapture,spansForRun,modelUsage,safeCloudUrl,type CloudCapture} from './cloudwatchData';
import type {AssuranceRun} from './assuranceData';
import {exportJson} from './evidenceApi';
const fmt=(v:any)=>v==null?'Not recorded':typeof v==='number'?v.toLocaleString():String(v);
export function CloudWatchTelemetry({run,sharedCapture}:{run:AssuranceRun;sharedCapture?:CloudCapture|null}){
 const [capture,setCapture]=useState<CloudCapture|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('Spans'),[agent,setAgent]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[range,setRange]=useState([0,100]),[ids,setIds]=useState<string[]>([]),[metric,setMetric]=useState('process.cpu.utilization'),[dimension,setDimension]=useState('');
 async function load(){try{const r=await fetch('data/cloudwatch-capture.json',{cache:'no-store'});if(!r.ok)throw Error('CloudWatch capture unavailable');setCapture(parseCloudCapture(await r.json()));setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(sharedCapture)setCapture(sharedCapture);else void load()},[sharedCapture]);useEffect(()=>{setSelected('');setIds([]);setRange([0,100]);setAgent('')},[run.id]);
 if(!capture)return <Alert severity={error?'warning':'info'}>{error||'Loading captured CloudWatch telemetry…'}</Alert>;
 const all=spansForRun(capture,run),usage=modelUsage(all),spans=all.filter(s=>(!agent||s.service===agent)&&(!query||JSON.stringify(s).toLowerCase().includes(query.toLowerCase())));
 const start=all.length?Math.min(...all.map(s=>Date.parse(s.startTime))):0,end=all.length?Math.max(...all.map(s=>Date.parse(s.endTime))):1;

 const visible=spans.filter(s=>(!ids.length||ids.includes(s.traceId+':'+s.spanId))&&Date.parse(s.startTime)>=start+(end-start)*range[0]/100&&Date.parse(s.startTime)<=start+(end-start)*range[1]/100),chosen=visible.find(s=>s.spanId===selected)??visible[0];
 const services=[...new Set(all.map(s=>s.service).filter(Boolean))],names=[...new Set(capture.metrics.flatMap(m=>Object.keys(m.measurements)))].sort(),metricSamples=capture.metrics.filter(m=>m.measurements[metric]!=null),dimensions=[...new Set(metricSamples.map(m=>JSON.stringify(m.dimensions)))],selectedDimension=dimensions.includes(dimension)?dimension:dimensions[0],samples=metricSamples.filter(m=>JSON.stringify(m.dimensions)===selectedDimension),max=Math.max(1e-12,...samples.map(m=>m.measurements[metric])),logs=capture.logs.filter(l=>all.some(s=>s.traceId===l.traceId));
 return <section className="cw-view"><div className="cw-provenance"><b>CloudWatch capture</b><span>{new Date(capture.capturedAt).toLocaleString('en-GB',{timeZone:'UTC'})} UTC · {capture.region}</span><Button onClick={load}>Reload capture</Button><Button component="label">Import capture<input hidden type="file" accept=".json,application/json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>10000000)throw Error('Capture exceeds 10 MB');setCapture(parseCloudCapture(JSON.parse(await f.text())));setError('')}catch(err){setError((err as Error).message)}finally{e.target.value=''}}}/></Button><Button onClick={()=>exportJson('cloudwatch-telemetry.json',capture)}>Export capture</Button></div>{error&&<Alert severity="error">{error}</Alert>}
 <div className="cw-tabs" role="tablist" aria-label="Telemetry type">{['Spans','Runtime metrics','Log metadata','Coverage'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Spans'&&<><div className="wa-statstrip"><MetricCard label="Matched spans · exact trace ID" value={all.length} icon="runs"/><MetricCard label="Model calls" value={usage.calls} icon="model"/><MetricCard label="Model-call tokens" value={fmt(usage.tokens)} icon="budget"/><MetricCard label="Saved budget comparison" value={usage.tokens==null||run.c16['measured.value']==null?'Not comparable':usage.tokens===run.c16['measured.value']?'✓ Totals agree':'Totals differ'} icon="verified"/></div><p className="cw-note">Only model-call spans contribute to token totals. Aggregate agreement does not prove a per-call budget match.</p>
 {all.length?<><div className="wa-toolbar"><TextField label="Search spans / trace ID" value={query} onChange={e=>{setQuery(e.target.value);setIds([])}}/><TextField select label="Agent" value={agent} onChange={e=>{setAgent(e.target.value);setIds([])}}><MenuItem value="">All agents</MenuItem>{services.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></div><SpanWaterfall spans={spans} selected={chosen?.spanId} onSelect={setSelected}/><div className="wa-split wa-span-split"><section className="wa-panel"><header><h2>Spans ({visible.length})</h2><span>Start time · UTC</span></header><PaginatedTable label="Spans" scrollClassName="wa-table-wrap wa-event-list" resetKey={run.id}><table><thead><tr><th>Time</th><th>Operation / agent</th><th>Duration</th><th>Status</th><th>Tokens</th></tr></thead><tbody>{visible.map(s=><tr className={chosen?.spanId===s.spanId?'selected':''} key={s.traceId+s.spanId}><td>{s.startTime.slice(11,23)}</td><td><button className="wa-link" onClick={()=>setSelected(s.spanId)}>{s.name}</button><small>{s.service}</small></td><td>{s.durationMs.toFixed(1)} ms</td><td>{s.status??'Unknown'}{s.httpStatus!=null&&` · HTTP ${s.httpStatus}`}</td><td>{s.operation==='chat'?fmt(s.totalTokens):'—'}</td></tr>)}</tbody></table></PaginatedTable></section><aside className="wa-panel wa-detail"><header><h2>Span evidence</h2><span>Observed CloudWatch fields</span></header><div className="wa-panel-scroll">{chosen&&<><dl>{Object.entries({'Operation':chosen.name,'Service':chosen.service,'Trace ID':chosen.traceId,'Span ID':chosen.spanId,'Parent span':chosen.parentSpanId,'Start (UTC)':chosen.startTime,'End (UTC)':chosen.endTime,'Duration (ms)':chosen.durationMs,'Model':chosen.model,'Input tokens':chosen.inputTokens,'Output tokens':chosen.outputTokens,'Tool':chosen.tool,'Tool call ID':chosen.toolCallId,'HTTP status':chosen.httpStatus,'Status':chosen.status,'Run linkage':'Exact trace ID in saved run evidence'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{fmt(v)}</dd></div>)}</dl><div className="wa-actions"><Button component="a" href={safeCloudUrl(chosen.sourceUrl)} target="_blank" rel="noopener noreferrer">Open CloudWatch ↗</Button></div><details><summary>Captured metadata</summary><pre>{JSON.stringify(chosen,null,2)}</pre></details></>}</div></aside></div></>:<Alert severity="info">No exact trace-ID match for this run in the current capture. No spans have been inferred from timing or agent names.</Alert>}</>}
 {tab==='Runtime metrics'&&<><p className="cw-note">Customer runtime samples · infrastructure scope, not attributed to the selected run. Counters are shown as captured values, not summed or converted to rates.</p><div className="wa-toolbar"><TextField select label="Metric" value={metric} onChange={e=>{setMetric(e.target.value);setDimension('')}} sx={{minWidth:330}}>{names.map(n=><MenuItem key={n} value={n}>{n}</MenuItem>)}</TextField><TextField select label="Metric dimensions" value={selectedDimension??''} onChange={e=>setDimension(e.target.value)}>{dimensions.map(d=><MenuItem key={d} value={d}>{Object.entries(JSON.parse(d)).map(([k,v])=>`${k}: ${v}`).join(' · ')||'No dimensions'}</MenuItem>)}</TextField></div><section className="wa-panel"><header><h2>{metric}</h2><span>{samples.length} captured samples</span></header><p className="cw-note" style={{padding:'0 22px'}}>Scale: 0 – {max} {samples[0]?.definitions?.find(d=>d.Name===metric)?.Unit??'source units'}</p><MetricLine samples={samples} metric={metric}/><div className="cw-metric-axis"><span>{samples[0]?.time}</span><span>{samples.at(-1)?.time}</span></div><PaginatedTable label="Runtime metrics" scrollClassName="wa-table-wrap wa-event-list" resetKey={JSON.stringify([metric,selectedDimension])}><table><thead><tr><th>Time · UTC</th><th>Value</th><th>Unit</th><th>Dimensions</th><th>Source</th></tr></thead><tbody>{samples.map((s,i)=><tr key={i}><td>{s.time}</td><td>{s.measurements[metric]}</td><td>{s.definitions?.find(d=>d.Name===metric)?.Unit??'Not recorded'}</td><td>{Object.entries(s.dimensions).map(([k,v])=>`${k}: ${v}`).join(' · ')}</td><td>{s.service}</td></tr>)}</tbody></table></PaginatedTable></section></>}
 {tab==='Log metadata'&&<section className="wa-panel"><header><h2>Trace-linked log metadata</h2><span>{logs.length} records for this run</span></header><p className="cw-note">Log bodies are excluded from this capture. Runtime metrics and logs were captured only from the customer stream's loaded page.</p><PaginatedTable label="Trace-linked log metadata" scrollClassName="wa-table-wrap" resetKey={run.id}><table><thead><tr><th>Timestamp</th><th>Severity</th><th>Trace ID</th><th>Span ID</th></tr></thead><tbody>{logs.map((l,i)=><tr key={i}><td>{l.time}</td><td>{l.severity}</td><td>{l.traceId}</td><td>{l.spanId}</td></tr>)}</tbody></table>{!logs.length&&<p className="wa-empty">No trace-linked logs in the captured page for this run. This does not establish that logs are absent in AWS.</p>}</PaginatedTable></section>}
 {tab==='Coverage'&&<section className="wa-panel"><header><h2>Capture scope & limitations</h2><span>Recorded provenance</span></header><div className="wa-evidence-body"><p>{capture.coverage}</p><p>{capture.omitted}</p><p>{capture.spans.length} unique spans · {capture.metrics.length} metric records · {capture.logs.length} log metadata records.</p><p>Captured services: {[...new Set(capture.spans.map(s=>s.service))].join(', ')}</p><p>Run correlation uses exact trace IDs from saved evidence. Session-name similarity and nearby timestamps do not establish a match.</p><p>Span status OK or HTTP 200 does not establish business workflow completion, control compliance, or notification delivery.</p><p>The supplied log-group screenshot showed a transformer error. Its cause and current state have not been established.</p></div></section>}
 </section>
}
