import {test} from 'node:test';import assert from 'node:assert/strict';
import {queryControl,statusClass,makeBundle,readBundle} from './controlQuery.ts';
const run=()=>({id:'real-test',c7:{verdict:'SATISFIED'},c7Threshold:{},c16:{verdict:'SATISFIED','evidence.refs':[{call_id:'a',at:'2026-10-05T00:00:00Z',threshold_version:'v1',input_tokens:8,output_tokens:3},{call_id:'b',at:'2026-10-05T00:01:00Z',threshold_version:'v1',input_tokens:2,output_tokens:1}]},c16Threshold:{version:'v1',cap:12,effective_at:'2026-10-04T00:00:00Z',exception_tolerance:0},expectedCallIds:['a','b'],budget:{},events:[]} as any);
test('recompute ignores stored pass and retains whole-run breach when window is small',()=>{const q=queryControl(run(),'16',[Date.parse('2026-10-05T00:01:00Z'),Date.parse('2026-10-05T00:02:00Z')]);assert.equal(q.verdict,'BREACH');assert.equal(q.measurement,14);assert.equal(q.windowMeasurement,3)});
test('missing call inventory and threshold provenance cannot pass',()=>{const r=run();delete r.expectedCallIds;delete r.c16Threshold.effective_at;assert.equal(queryControl(r,'16').verdict,'INSUFFICIENT EVIDENCE')});
test('duplicate calls invalidate measurement rather than silently double count',()=>{const r=run();r.c16['evidence.refs'].push(r.c16['evidence.refs'][0]);const q=queryControl(r,'16');assert.equal(q.verdict,'INSUFFICIENT EVIDENCE');assert.equal(q.measurement,null)});
test('unknown status is distinct from breach',()=>{for(const v of ['NO EVIDENCE','INCONCLUSIVE',undefined])assert.equal(statusClass(v),'unknown')});
test('bundle tampering is detected',async()=>{const b=await makeBundle({runs:[]} as any);assert.ok(await readBundle(b));b.payload.assurance.runs.push(run());await assert.rejects(()=>readBundle(b),/checksum/)});
test('C7 does not claim independent coverage from a saved report mapping',()=>{const r=run();r.c7.source_refs={event:'ledger:1'};assert.equal(queryControl(r,'7').verdict,'INSUFFICIENT EVIDENCE')});
test('C16 rejects a relaxed over-cap exception rate',()=>{const r=run();r.c16Threshold.exception_tolerance=1;assert.equal(queryControl(r,'16').verdict,'INSUFFICIENT EVIDENCE')});
test('C7 independently counts expected records and recording gaps',()=>{const r=run();r.c7Threshold={coverage_target:1,gap_limit_ms:5,exception_tolerance:0,declared_at:'2026-10-04T00:00:00Z'};r.expectedEvents=[{id:'x',source:'ledger:1',time:'2026-10-05T00:00:00Z'},{id:'y',source:'ledger:2',time:'2026-10-05T00:00:00.008Z'}];r.events=r.expectedEvents.map((e:any)=>({...e,event_id:e.id}));const q=queryControl(r,'7');assert.equal(q.verdict,'BREACH');assert.equal(q.coverage,1);assert.equal(q.exceptions,1);assert.equal(q.windowMeasurement,8)});

test('C9 requires frozen baseline, bound windows and independent inventory',()=>{const r=run();Object.assign(r,{qualityBaseline:{value:0.9,metric:'quality',version:'b1',frozen_at:'2026-10-01T00:00:00Z'},c9Threshold:{version:'q1',metric:'quality',declared_at:'2026-10-01T00:00:00Z',max_absolute_drift:0.1,allowed_exception_rate:0},qualityWindows:[{id:'w1',value:0.85,metric:'quality',baseline_version:'b1',threshold_version:'q1',start:'2026-10-05T00:00:00Z',end:'2026-10-05T00:01:00Z'}],expectedQualityWindowIds:['w1']});assert.equal(queryControl(r,'9').verdict,'PASS');r.qualityWindows[0].value=0.5;assert.equal(queryControl(r,'9').verdict,'BREACH');r.qualityWindows[0].baseline_version='other';assert.equal(queryControl(r,'9').verdict,'INSUFFICIENT EVIDENCE');delete r.expectedQualityWindowIds;assert.equal(queryControl(r,'9').verdict,'INSUFFICIENT EVIDENCE')});
test('C9 cannot use a baseline frozen after the scored window',()=>{const r=run();Object.assign(r,{qualityBaseline:{value:1,metric:'q',version:'b',frozen_at:'2026-10-06T00:00:00Z'},c9Threshold:{version:'v',metric:'q',declared_at:'2026-10-01T00:00:00Z',max_absolute_drift:1,allowed_exception_rate:0},qualityWindows:[{id:'w',value:1,metric:'q',baseline_version:'b',threshold_version:'v',start:'2026-10-05T00:00:00Z',end:'2026-10-05T00:01:00Z'}],expectedQualityWindowIds:['w']});assert.equal(queryControl(r,'9').verdict,'INSUFFICIENT EVIDENCE')});
