import {formatUTCDate,formatUTCTime,formatUTCDateTime} from './dateTime';
import {useState} from 'react';
import {Button,Slider} from '@mui/material';
import {failed,timeBuckets,categories,category,colors,type AssuranceEvent} from './assuranceData';
const clock=(v:number)=>formatUTCTime(v);
type Props={variant?:'bars'|'markers';events:AssuranceEvent[];start:number;end:number;range:number[];onRange:(r:number[])=>void;onInspect:(ids:string[])=>void;selectedIds:string[]};
export function DenseTimeline({variant='bars',events,start,end,range,onRange,onInspect,selectedIds}:Props){
 const [hover,setHover]=useState<number|null>(null),[clusters,setClusters]=useState(false);
 const duration=Math.max(1,end-start),lo=start+duration*range[0]/100,hi=start+duration*range[1]/100;
 const buckets=timeBuckets(events,lo,hi,Math.max(1,(hi-lo)/(clusters?24:120))),overview=timeBuckets(events,start,end,Math.max(1,duration/160));
 const peak=Math.max(1,...buckets.map(b=>b.events.length)),overviewPeak=Math.max(1,...overview.map(b=>b.events.length));
 const selected=buckets.findIndex(b=>b.events.length>0&&b.events.some(e=>selectedIds.includes(e.id))),active=hover==null?(selected<0?null:buckets[selected]):buckets[hover];
 const marker=hover??(selected<0?null:selected),unknown=events.filter(e=>!e.time).length;
 function setWindow(width:number){const w=Math.min(100,Math.max(.1,width)),center=(range[0]+range[1])/2,left=Math.max(0,Math.min(100-w,center-w/2));onRange([left,left+w]);onInspect([]);setHover(null)}
 const total=buckets.reduce((n,b)=>n+b.events.length,0);
 return <section className="rt" aria-label="Event volume timeline">
 <header className="rt-heading"><div><span className="rt-icon" aria-hidden="true">▥</span><h3>Event timeline</h3></div><span className="rt-date">▦ {formatUTCDate(start)} · UTC</span></header>
 <div className="rt-toolbar"><div className="rt-zoom"><span>Zoom</span><div><Button aria-label="Zoom out" disabled={range[0]===0&&range[1]===100} onClick={()=>setWindow((range[1]-range[0])*2)}>−</Button>{[{label:'Full run',width:100},{label:'20s',width:20000/duration*100},{label:'10s',width:10000/duration*100},{label:'5s',width:5000/duration*100}].map(x=><Button key={x.label} aria-pressed={Math.abs(range[1]-range[0]-Math.min(100,x.width))<.01} onClick={()=>setWindow(x.width)}>{x.label}</Button>)}<Button aria-label="Zoom in" onClick={()=>setWindow((range[1]-range[0])/2)}>+</Button></div></div><label className="rt-cluster-toggle"><input type="checkbox" checked={clusters} onChange={e=>{setClusters(e.target.checked);setHover(null)}}/>Show clusters</label><div className="rt-window"><span>{((hi-lo)/1000).toFixed(1)} seconds selected</span><b>{clock(lo)} – {clock(hi)}</b></div></div>
 <div className="rt-overview"><div className="rt-mini" aria-hidden="true">{overview.map(b=><span key={b.start} style={{height:`${b.events.length/overviewPeak*76}%`}}/>)}</div><div className="rt-brush" aria-hidden="true" style={{left:`${range[0]}%`,width:`${range[1]-range[0]}%`}}/><Slider className="rt-slider" value={range} onChange={(_,v)=>{onRange(v as number[]);onInspect([]);setHover(null)}} disableSwap min={0} max={100} step={.1} getAriaLabel={i=>i?'Window end':'Window start'} getAriaValueText={v=>clock(start+duration*v/100)+' UTC'}/></div>
 <div className="rt-overview-axis">{[0,.25,.5,.75,1].map(t=><span key={t}>{clock(start+duration*t)}</span>)}</div>
 <div className="rt-periods">{[0,1,2,3,4,5].map(i=><div key={i}><b>{clock(lo+(hi-lo)*i/6)}</b><span>{i===0?'Window start':`${Math.round((hi-lo)*i/6000)}s elapsed`}</span></div>)}</div>
 <div className="rt-main"><div className="rt-metric">Source records <span>Peak {peak} / interval</span></div>{variant==='markers'?<div className="rt-event-markers" role="group" aria-label="Individual events by time">{events.filter(e=>e.time&&Date.parse(e.time)>=lo&&Date.parse(e.time)<=hi).map(e=>{const c=category(e),idx=categories.indexOf(c),isFailure=failed(e);return <button key={e.id} aria-label={`${formatUTCDateTime(e.time)} UTC ${c} ${e.phase??'Transport attempt'} ${e.actor??'Unknown actor'}${isFailure?' Failure or refusal':''}`} aria-pressed={selectedIds.includes(e.id)} title={`${c} · ${e.phase??'Transport attempt'} · ${e.actor??'Unknown actor'}`} style={{left:`${2+(Date.parse(e.time!)-lo)/Math.max(1,hi-lo)*96}%`,height:`${25+idx*12}px`,color:isFailure?'#d85454':colors[c]}} onClick={()=>onInspect([e.id])}><span>{['A','M','T','✓','$','↗'][idx]}</span></button>})}</div>:(<div className={`rt-bars ${clusters?'rt-cluster-bars':''}`} role="group" aria-label="Record counts by time interval">{buckets.map((b,i)=>{const selected=b.events.length>0&&b.events.some(e=>selectedIds.includes(e.id));return <button key={b.start} className={selected?'is-selected':''} disabled={!b.events.length} aria-pressed={selected} aria-label={`${new Date(b.start).toISOString().slice(11,23)} UTC: ${b.events.length} records, ${b.events.filter(failed).length} failures or refusals. Inspect records`} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(i)} onBlur={()=>setHover(null)} onClick={()=>onInspect(selected?[]:b.events.map(e=>e.id))}><span className="rt-column" style={{height:`${b.events.length/peak*82}%`}}>{clusters&&b.events.length>0&&<span className="rt-cluster-bubble"><b>{b.events.length}</b><small>records</small></span>}</span></button>})}</div>)}
 {marker!=null&&<div className="rt-cursor" aria-hidden="true" style={{left:`${Math.min(99,(marker+.5)/buckets.length*100)}%`}}><span>{clock(buckets[marker].start)}</span></div>}
 </div>
 <div className="rt-axis">{[0,.125,.25,.375,.5,.625,.75,.875,1].map(t=><span key={t}>{clock(lo+(hi-lo)*t)}</span>)}</div>
 <div className="rt-legend">{categories.map(c=><span key={c}><i style={{background:colors[c]}}/>{c}</span>)}<span><i style={{background:'#d85454'}}/>Failure</span><span className="rt-caption">{variant==='markers'?'Markers = individual records':'Height = record count'}</span></div>
 <div className="rt-context" aria-live="polite">{active?<><b>{active.events.length} records</b><span>{clock(active.start)} · {active.events.filter(failed).length} failures / refusals</span></>:<><b>{total} records in view</b><span>{variant==='markers'?'Select a marker to inspect its evidence below':'Select a bar to inspect its evidence below'}</span></>}{selectedIds.length>0&&<Button size="small" onClick={()=>onInspect([])}>Clear selection</Button>}</div>
 {unknown>0&&<p className="rt-unknown">{unknown} records without timestamps are available in the full-run list.</p>}
 </section>
}
