import {useState} from 'react';
import {Box,Typography,Tooltip,IconButton,TextField,MenuItem,Button,Table,TableBody,TableCell,TableHead,TableRow,TableContainer} from '@mui/material';
import InfoOutlined from '@mui/icons-material/InfoOutlined';
import {LineChart} from '@mui/x-charts/LineChart';
import {Gauge,gaugeClasses} from '@mui/x-charts/Gauge';
import {PieChart} from '@mui/x-charts/PieChart';
import {controls,evaluate,rules,type Run,type Control} from './evidence';
import {summarize} from './evidenceApi';
export function ChartHelp({text}:{text:string}){return <Tooltip title={text}><IconButton size="small" aria-label={text}><InfoOutlined sx={{fontSize:17}}/></IconButton></Tooltip>}
export function Radial({value,total,label,color='#4285f4'}:{value:number;total:number;label:string;color?:string}){return <Tooltip title={`${label}: ${value} of ${total}. ${total?Math.round(value/total*100):0}% of sample records.`}><Box tabIndex={0} role="img" aria-label={`${label}: ${value} of ${total}`} sx={{width:150,maxWidth:'100%'}}><Gauge height={125} value={total?value/total*100:0} startAngle={-110} endAngle={110} innerRadius="77%" text={`${value}/${total}`} sx={{[`& .${gaugeClasses.valueArc}`]:{fill:color},[`& .${gaugeClasses.referenceArc}`]:{fill:'var(--border)'},[`& .${gaugeClasses.valueText} text`]:{fontSize:26,fontWeight:600,fill:'var(--text)'}}}/><Typography variant="caption" display="block" textAlign="center">{label}</Typography></Box></Tooltip>}
export function RunTrend({runs,initialControl='9',fixedRun}:{runs:Run[];initialControl?:Control;fixedRun?:Run}){
 const [control,setControl]=useState<Control>(initialControl),[runId,setRunId]=useState('alpha-002'),[table,setTable]=useState(false);
 const c=fixedRun?initialControl:control;const run=fixedRun??runs.find(r=>r.id===runId)??runs[0];if(!run)return <Typography>No run measurements received.</Typography>;
 const values=run.values[c];const limit=c==='7'?6:c==='9'?110:rules[c].limit;const unit=c==='7'?'events':c==='9'?'ms':'tokens';
 const data=values.map(v=>v===null?null:v);
 return <Box><Box className="visual-heading"><div><Typography variant="h6">{c==='9'?'Where did performance drift?':c==='7'?'Were expected events captured?':'How much of the run budget was used?'}</Typography><Typography variant="caption" color="text.secondary">{run.id} · two observed one-minute windows · sample data</Typography></div><ChartHelp text={c==='9'?'Latency baseline is 100 ms. The permitted band is 90–110 ms. Each point represents a window measurement.':c==='7'?'Six unique governed events are expected per window. A missing measurement remains a gap.':'Tokens are cumulative from run start. The sample cap is 1,000 tokens; runtime blocking is not implemented.'}/></Box>
 {!fixedRun&&<Box display="flex" gap={2} flexWrap="wrap" my={2}><TextField select label="Run" value={run.id} onChange={e=>setRunId(e.target.value)} size="small" sx={{minWidth:150}}>{runs.map(r=><MenuItem key={r.id} value={r.id}>{r.id}</MenuItem>)}</TextField><TextField select label="Control" value={c} onChange={e=>setControl(e.target.value as Control)} size="small" sx={{minWidth:200}}>{controls.map(id=><MenuItem value={id} key={id}>{rules[id].name}</MenuItem>)}</TextField></Box>}
 <LineChart height={270} xAxis={[{scaleType:'point',data:['10:01','10:02'],label:'Window ending · UTC'}]} yAxis={[{min:0,label:unit}]} series={[{id:'measurement',data,label:c==='9'?'Measured latency':c==='7'?'Recorded events':'Cumulative tokens',color:'#4285f4',area:true,curve:'linear',connectNulls:false,valueFormatter:v=>v===null?'Missing':`${v} ${unit}`},{id:'limit',data:values.map(()=>limit),label:c==='9'?'Upper limit':c==='7'?'Expected':'Cap',color:'#ea4335',showMark:false,valueFormatter:v=>`${v} ${unit}`},...(c==='9'?[{id:'lower',data:[90,90],label:'Lower limit',color:'#fbbc05',showMark:false},{id:'baseline',data:[100,100],label:'Baseline',color:'#34a853',showMark:false}]:[])]} grid={{horizontal:true}} skipAnimation sx={{'& .MuiAreaElement-root':{fillOpacity:.13},'& .MuiLineElement-series-limit,& .MuiLineElement-series-lower':{strokeDasharray:'5 4'}}}/>
 <Button size="small" onClick={()=>setTable(!table)} aria-expanded={table}>{table?'Hide':'View'} chart data</Button>{table&&<TableContainer><Table size="small" aria-label="Trend chart data"><TableHead><TableRow><TableCell>Window (UTC)</TableCell><TableCell>Measured</TableCell><TableCell>Reference</TableCell></TableRow></TableHead><TableBody>{values.map((v,i)=><TableRow key={i}><TableCell>10:0{i}–10:0{i+1}</TableCell><TableCell>{v===null?'Missing':`${v} ${unit}`}</TableCell><TableCell>{c==='9'?'90–110 ms':`${limit} ${unit}`}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}
 </Box>
}
export function OverviewVisuals({runs}:{runs:Run[]}){const stats=summarize(runs);return <Box className="analysis-layout"><Box className="analysis-main"><RunTrend runs={runs}/></Box><Box className="analysis-aside"><Typography variant="h6">Which runs satisfy the checks?</Typography><Typography variant="caption" color="text.secondary">Full-run sample verdicts</Typography><PieChart height={220} series={[{innerRadius:65,outerRadius:85,paddingAngle:4,cornerRadius:5,data:[{id:'pass',value:stats.passing,label:'Pass',color:'#34a853'},{id:'breach',value:stats.breaching,label:'Breach',color:'#ea4335'},{id:'unknown',value:stats.incomplete,label:'Incomplete',color:'#fbbc05'}],valueFormatter:item=>`${item.value} of ${stats.total} sample runs`}]} skipAnimation/>
 <Typography variant="body2" color="text.secondary">{stats.passing} passing · {stats.breaching} breached · {stats.incomplete} incomplete</Typography><Typography variant="caption" color="text.secondary" display="block" mt={1}>Incomplete runs may also contain known breaches.</Typography><Box className="control-rings">{controls.map(c=><Radial key={c} value={runs.filter(r=>evaluate(r,c).verdict==='Pass').length} total={runs.length} label={`C${c} passing`} color={c==='7'?'#4285f4':c==='9'?'#34a853':'#fbbc05'}/>)}</Box></Box></Box>}
