import {useEffect,useRef,useState} from 'react';
import {Alert,Button,MenuItem,TextField} from '@mui/material';
type Job={id:string;runId:string;scenario:string;state:string;createdAt:string;message?:string;traceId?:string;thresholdVersion?:string;exitCode?:number;collectionExitCode?:number;invokedAgents?:string[]};
async function response(r:Response){const d=await r.json();if(!r.ok)throw Error(d.error||'Execution service unavailable');return d}
export function ExecutionPanel({onInspect,onRefresh}:{onInspect:(id:string)=>void;onRefresh:()=>void}){
 const [config,setConfig]=useState<any>(null),[jobs,setJobs]=useState<Job[]>([]),[scenario,setScenario]=useState(''),[error,setError]=useState(''),[launching,setLaunching]=useState(false),[uncertain,setUncertain]=useState(false);
 const request=useRef<{scenario:string;idempotencyKey:string}|null>(null),states=useRef('');
 async function load(){try{const [c,j]=await Promise.all([fetch('api/execution-config',{cache:'no-store'}).then(response),fetch('api/executions',{cache:'no-store'}).then(response)]);setConfig(c);setJobs(j.executions);setScenario(s=>s||c.scenarios[0]?.id||'');const next=JSON.stringify(j.executions.map((x:Job)=>[x.id,x.state]));if(states.current&&next!==states.current)onRefresh();states.current=next;setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load();const t=setInterval(()=>{if(!document.hidden)void load()},5000);return()=>clearInterval(t)},[]);
 async function launch(){if(!request.current)request.current={scenario,idempotencyKey:crypto.randomUUID()};setLaunching(true);try{const r=await fetch('api/executions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request.current),signal:AbortSignal.timeout(15000)});if(!r.ok){const d=await r.json();if(r.status<500){request.current=null;setUncertain(false)}throw Error(d.error||'Launch rejected')}await response(r);request.current=null;setUncertain(false);await load()}catch(e){setError((e as Error).message);setUncertain(!!request.current)}finally{setLaunching(false)}}
 const active=jobs.some(j=>['queued','running','collecting','interrupted'].includes(j.state));
 return <section className="wa-panel"><header><h2>Run execution</h2><span>Deployed runner</span><Button onClick={load}>Refresh executions</Button></header>{error&&<Alert severity="warning">{error}</Alert>}<div className="wa-toolbar"><TextField select label="Scenario" value={scenario} disabled={!config||launching||uncertain} onChange={e=>setScenario(e.target.value)} sx={{minWidth:240}}>{config?.scenarios.map((s:any)=><MenuItem key={s.id} value={s.id}>{s.title}</MenuItem>)}</TextField><Button variant="contained" onClick={launch} disabled={launching||!config?.enabled||!scenario||(active&&!uncertain)}>{launching?'Submitting…':uncertain?'Check / retry same launch':'Start run'}</Button></div>{config&&<p>Threshold {config.threshold.version??'Unavailable'} · declared {config.threshold.declaredAt??'Unavailable'}. Each run pins the configuration before invoking the deployed agents.</p>}{uncertain&&<Alert severity="info">The launch response was not received. Retrying uses the same request ID to prevent a duplicate execution.</Alert>}<div className="wa-table-wrap"><table><thead><tr><th>Run / scenario</th><th>Execution state</th><th>Created · UTC</th><th>Evidence</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td>{j.runId}<small>{j.scenario}</small></td><td>{j.state}<small>{j.invokedAgents?.length?`Invoked: ${j.invokedAgents.join(", ")}`:""}</small><small>{j.message}</small></td><td>{j.createdAt}</td><td><Button onClick={()=>onInspect(j.runId)}>Inspect collected evidence</Button></td></tr>)}</tbody></table>{config&&!jobs.length&&<p>No executions have been submitted through this service.</p>}</div><footer>Execution completion, evidence collection and control validation are separate results.</footer></section>
}
