import {useState} from 'react';
import {Alert,Button,TextField,MenuItem} from '@mui/material';
import {queryControl,statusClass,makeBundle,readBundle} from './controlQuery';
import {parseAssurance,type AssuranceRun,type AssuranceData} from './assuranceData';
import {exportJson} from './evidenceApi';
import {workshopLinks} from './workshopEvidence';
import {parseCloudCapture,type CloudCapture} from './cloudwatchData';
export const serviceNowImport='https://platformdemoh8.service-now.com/sys_concurrent_import_set.do?sys_id=936f843c3b7b8350e837212c95e45a97';
const fmt=(v:any)=>v==null?'Not recorded':typeof v==='object'?JSON.stringify(v):String(v);
export function QueryPanel({run,control='16',window}:{run:AssuranceRun;control?:string;window?:[number,number]}){
 const [result,setResult]=useState<ReturnType<typeof queryControl>|null>(null);const key=JSON.stringify([run.id,control,window]);const [checked,setChecked]=useState('');const current=checked===key?result:null;
 return <section className="wa-panel hx-query"><header><h2>Independent control query</h2><span>{run.id} · Control {control}</span><Button variant="contained" onClick={()=>{setResult(queryControl(run,control,window));setChecked(key)}}>Recompute evidence</Button></header>{current?<><div className="hx-result"><span className={`wa-badge ${statusClass(current.verdict)}`}>{current.verdict}</span><span>Measured <b>{fmt(current.measurement)}</b></span><span>Limit <b>{fmt(current.limit)}</b></span><span>Coverage <b>{current.coverage==null?'Unknown':`${(current.coverage*100).toFixed(1)}%`}</b></span><span>Exception rate <b>{current.exceptionRate==null?'Unknown':`${current.exceptionRate*100}%`}</b></span></div><p>{current.scope} · {current.algorithm}. {control==='16'?`Window usage: ${fmt(current.windowMeasurement)} tokens. The full run cap is retained.`:`Maximum eligible gap: ${fmt(current.windowMeasurement)} ms; coverage denominator: ${current.denominator}.`}</p><p>{current.enforcement}</p>{current.gaps.length>0&&<details><summary>{current.gaps.length} evidence gaps</summary>{current.gaps.map(g=><p key={g}>{g}</p>)}</details>}<details><summary>{current.refs.length} supporting record IDs</summary><pre>{JSON.stringify(current.refs,null,2)}</pre></details><Button onClick={()=>exportJson(`${run.id}-recomputed-C${control}.json`,current)}>Export query result</Button></>:<p>Select recompute to calculate from the exported records. A saved verdict is not used as the calculation result.</p>}</section>
}
export function RegisterPanel({run,control}:{run:AssuranceRun;control:string}){
 const t=control==='7'?run.c7Threshold:control==='16'?run.c16Threshold??run.budget.threshold??{}:{};
 const fields={'Control':control,'Statement':control==='7'?'Required actions are recorded and eligible recording gaps remain within the declared tolerance':control==='16'?'Input and output tokens across agents and retries stay within the declared per-run cap':'Quality drift remains within a frozen baseline tolerance','Objective':control==='7'?'Accountable, complete event recording':control==='16'?'Bound model spend':'Detect quality degradation','Owner':t.owner,'Applicable scope':t.scope??t.metric,'Version':t.version,'Effective / declared at':t.effective_at??t.declared_at,'Version date (not exact effective time)':t.version_date,'Allowed exception rate':t.exception_tolerance??t.allowed_exception_rate,'Enforcement point':t.enforcement_point,'Declared budget mode (not enforcement proof)':run.budget.mode,'Rationale':t.why_this_value,'Instrument / obligation':t.instrument??t.obligation,'Test frequency':t.frequency,'Procedure':control==='7'?'Reconcile expected actions; measure gaps between unique eligible event timestamps':control==='16'?'Deduplicate leaf calls and retries; reconcile expected inventory; sum input + output tokens':'Compare scored windows to dated baseline'};
 return <section className="wa-panel"><header><h2>Control definition & ownership</h2><span>Declared fields remain visible when missing</span></header><dl className="hx-facts">{Object.entries(fields).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{fmt(v)}</dd></div>)}</dl>{control==='7'&&<div className="hx-result"><span>Eligible gaps <b>{fmt(run.c7.gap_count)}</b></span><span>Max gap <b>{fmt(run.c7.max_gap_ms)} ms</b></span><span>Gap limit <b>{fmt(run.c7.gap_limit_ms)} ms</b></span><span>Violations <b>{fmt(run.c7.gap_violations?.length)}</b></span><span>Timing result <b>{fmt(run.c7.timing_verdict)}</b></span></div>}</section>
}
export function SpendChart({run}:{run:AssuranceRun}){
 const calls=run.c16['evidence.refs']??[];let total=0;const rows=calls.map((c:any)=>{const valid=Number.isInteger(c.input_tokens)&&Number.isInteger(c.output_tokens)&&c.input_tokens>=0&&c.output_tokens>=0;total+=valid?c.input_tokens+c.output_tokens:0;return {...c,total,valid}});const cap=Number(run.c16['threshold.value']),max=Math.max(1,Number.isFinite(cap)?cap:0,total)*1.1;const points=rows.flatMap((r:any,i:number)=>{const x=45+(i+1)/Math.max(1,rows.length)*900,y=170-r.total/max*140,previous=i?rows[i-1].total:0;return [`${x},${170-previous/max*140}`,`${x},${y}`]}).join(' ');
 return <section className="wa-panel"><header><h2>Gateway token accumulation</h2><span>Whole run · recorded leaf calls</span></header>{rows.length?<><svg className="hx-spend" viewBox="0 0 980 220" role="img" aria-label={`Cumulative recorded usage ${total} tokens; limit ${Number.isFinite(cap)?cap:'unknown'}`}><line x1="45" x2="945" y1="170" y2="170" stroke="var(--border)"/>{Number.isFinite(cap)&&<><line x1="45" x2="945" y1={170-cap/max*140} y2={170-cap/max*140} stroke="var(--chart-budget)" strokeDasharray="5 4"/><text x="45" y={160-cap/max*140}>Cap {cap.toLocaleString()}</text></>}<polyline points={`45,170 ${points}`} fill="none" stroke="var(--primary)" strokeWidth="2"/>{rows.map((r:any,i:number)=><circle key={i} cx={45+(i+1)/rows.length*900} cy={170-r.total/max*140} r="4" fill={r.total>cap?'var(--chart-failure)':'var(--primary)'}><title>{r.call_id}: {r.total} cumulative tokens</title></circle>)}<text x="45" y="205">First call</text><text x="945" y="205" textAnchor="end">{rows.length} calls · {total.toLocaleString()} tokens</text></svg><details><summary>Per-call input / output and cumulative usage</summary><div className="wa-table-wrap"><table><thead><tr><th>Call ID</th><th>Time UTC</th><th>Input</th><th>Output</th><th>Cumulative</th></tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i}><td>{r.call_id}</td><td>{r.at}</td><td>{r.input_tokens}</td><td>{r.output_tokens}</td><td>{r.valid?r.total:'Usage missing'}</td></tr>)}</tbody></table></div></details><p>Recorded usage only. Missing inventory, retries or decision bindings remain query gaps.</p></>:<p>No per-call gateway usage is supplied for this run.</p>}</section>
}
export function ReadinessPanel({data,onRun}:{data:AssuranceData;onRun:(id:string)=>void}){
 const [checked,setChecked]=useState(false);const assessments=data.runs.map(run=>({run,c7:queryControl(run,'7'),c16:queryControl(run,'16')}));
 return <section className="wa-panel hx-readiness"><header><h2>Control assurance across the workspace</h2><span>Saved evaluations and independent checks are separate</span><Button onClick={()=>setChecked(true)}>Check all runs</Button></header><div className="wa-table-wrap" style={{maxHeight:230}}><table><thead><tr><th>Run</th><th>C7 · recording</th><th>C16 · spend</th><th>Independent C7</th><th>Independent C16</th></tr></thead><tbody>{assessments.map(({run,c7,c16})=><tr key={run.id}><td><button className="wa-link" onClick={()=>onRun(run.id)}>{run.id}</button></td><td><span className={`wa-badge ${statusClass(run.c7.verdict)}`}>{statusClass(run.c7.verdict)==='good'?'✓ ':''}{run.c7.verdict??'Not assessed'}</span></td><td><span className={`wa-badge ${statusClass(run.c16.verdict)}`}>{statusClass(run.c16.verdict)==='good'?'✓ ':''}{run.c16.verdict??'Not assessed'}</span></td><td>{checked?c7.verdict:'Not checked'}</td><td>{checked?c16.verdict:'Not checked'}</td></tr>)}</tbody></table></div><footer>Independent checks recompute exported evidence and require the declared threshold and expected inventory. Open a run to inspect its exact query gaps.</footer></section>
}
export function OfflinePanel({data,onImport,telemetry}:{data:AssuranceData;telemetry?:CloudCapture|null;onImport:(data:AssuranceData,telemetry?:CloudCapture)=>void}){
 const [message,setMessage]=useState(''),[error,setError]=useState('');
 return <section className="wa-panel"><header><h2>Portable audit bundle</h2><span>Independent browser recomputation · no API required</span></header><div className="wa-actions"><Button variant="outlined" onClick={async()=>{try{let captured=telemetry??null;if(!captured)try{const r=await fetch('data/cloudwatch-capture.json');captured=parseCloudCapture(await r.json())}catch{};let foundation=null;try{const response=await fetch('data/foundation-preflight.json');if(response.ok)foundation=await response.json()}catch{};let governanceObservation=null;try{const response=await fetch('data/governance-browser-observation.json');if(response.ok)governanceObservation=await response.json()}catch{};const findingHistory=JSON.parse(localStorage.getItem('alpha-finding-history')??'[]');exportJson('alpha-audit-bundle.json',await makeBundle(data,{telemetry:captured,findingHistory,governanceObservation,foundation}));setMessage('Bundle exported with evidence, telemetry and local finding history.')}catch(e){setError((e as Error).message)}}}>Export audit bundle</Button><Button component="label">Import & verify bundle<input hidden type="file" accept=".json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>20000000)throw Error('Bundle exceeds 20 MB');const p=await readBundle(JSON.parse(await f.text()));const importedData=parseAssurance(p.assurance);const importedTelemetry=p.telemetry?parseCloudCapture(p.telemetry):undefined;if(Array.isArray(p.findingHistory)){const existing=JSON.parse(localStorage.getItem('alpha-finding-history')??'[]');const merged=[...existing];for(const entry of p.findingHistory)if(entry&&typeof entry.findingId==='string'&&!merged.some(x=>JSON.stringify(x)===JSON.stringify(entry)))merged.push(entry);localStorage.setItem('alpha-finding-history',JSON.stringify(merged))}onImport(importedData,importedTelemetry);setMessage('Checksum matches. Imported evidence can be recomputed locally. Origin and authenticity are not verified.');setError('')}catch(err){setError((err as Error).message)}finally{e.target.value=''}}}/></Button></div>{message&&<Alert severity="info">{message}</Alert>}{error&&<Alert severity="error">{error}</Alert>}<Button component="a" href="downloads/alpha-independent-reproduction.zip" download>Download offline checker</Button><p>SHA-256 detects changes relative to this bundle checksum. It does not authenticate the source or prove completeness. Keep the original bundle and declared threshold records.</p></section>
}
export function ServiceNowPanel(){const [embed,setEmbed]=useState(false),[view,setView]=useState('Import record');const links:Record<string,string>={'Import record':serviceNowImport,'Control Tower':workshopLinks.servicenow,'Agent Studio':workshopLinks.studio};const url=links[view];return <section className="wa-panel hx-servicenow"><header><h2>ServiceNow · Alpha AWS usage import</h2><span>CISET0021161 · browser access</span><Button component="a" href={url} target="_blank" rel="noopener noreferrer">Open in browser ↗</Button><Button onClick={()=>setEmbed(!embed)}>{embed?'Close embedded view':'Show embedded view'}</Button></header><div className="wa-toolbar"><TextField select label="ServiceNow browser view" value={view} onChange={e=>setView(e.target.value)}>{Object.keys(links).map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><span>Embedding did not render in the Chrome acceptance check. Open in browser is available.</span></div><div className="hx-result"><span>CloudWatch requests <b>2 × HTTP 200</b></span><span>STS requests <b>3 × HTTP 200</b></span><span>SageMaker request <b className="hx-error">HTTP 400</b></span><span>Transform rows <b className="hx-error">0 processed</b></span><Button component="a" href="https://platformdemoh8.service-now.com/sys_import_set_run.do?sys_id=ff9f403ceb734750429ef4ffbad0cd89" target="_blank" rel="noopener noreferrer">Inspect TH0026475 ↗</Button></div><p>Observed on 5 Oct 2026 in the supplied authenticated browser record. Transform TH0026475 was inspected in the authenticated browser: Complete, 0 total, 0 processed, 0 inserts, 0 updates, 0 errors. Successful requests have not yielded imported usage in this record. Per-run linkage and finding delivery are not established. Source display times have no verified timezone.</p>{embed&&<><Alert severity="info">Use your existing ServiceNow login. If this instance blocks framing or third-party cookies, open the record in the browser. The app cannot inspect cross-origin content or infer success from iframe load.</Alert><iframe title="ServiceNow Alpha concurrent import record" src={url} referrerPolicy="no-referrer" loading="lazy" sandbox="allow-scripts allow-same-origin allow-forms allow-popups"/><Button component="a" href={url} target="_blank" rel="noopener noreferrer">Embedded view unavailable? Open ServiceNow ↗</Button></>}</section>}
export function FindingLifecycle({run}:{run:AssuranceRun}){
 const originals=['7','16'].filter(c=>statusClass((c==='7'?run.c7:run.c16).verdict)==='bad').map(c=>({id:`${run.id}:C${c}`,control:c,original:(c==='7'?run.c7:run.c16)}));
 const [history,setHistory]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem('alpha-finding-history')??'[]')}catch{return []}}),[owner,setOwner]=useState(''),[action,setAction]=useState('Remediate'),[note,setNote]=useState(''),[expiry,setExpiry]=useState(''),[retest,setRetest]=useState(''),[error,setError]=useState('');
 return <section className="wa-panel"><header><h2>Control findings & disposition</h2><span>Local audit notes · no external notification sent</span></header>{originals.length?originals.map(f=><div className="hx-finding" key={f.id}><b>{f.id}</b><details><summary>Original breach evidence (preserved)</summary><pre>{JSON.stringify(f.original,null,2)}</pre></details><div className="wa-toolbar"><TextField label="Accountable person" value={owner} onChange={e=>setOwner(e.target.value)}/><TextField select label="Disposition" value={action} onChange={e=>setAction(e.target.value)}>{['Remediate','Temporary compensation','Accept risk'].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField label="Action / evidence reference" value={note} onChange={e=>setNote(e.target.value)}/><TextField label="Expiry (UTC)" placeholder="2026-10-06T12:00:00Z" value={expiry} onChange={e=>setExpiry(e.target.value)}/><TextField label="Retest run reference" value={retest} onChange={e=>setRetest(e.target.value)}/><Button onClick={()=>{if(!owner.trim()||!note.trim()||(action!=='Remediate'&&(!Number.isFinite(Date.parse(expiry))||Date.parse(expiry)<=Date.now()))){setError('Person and action are required; compensation/risk acceptance needs a future expiry.');return}const next=[...history,{findingId:f.id,owner,action,note,expiry:expiry||null,retest:retest||null,at:new Date().toISOString(),status:'Recorded local disposition; action and retest not verified'}];setHistory(next);localStorage.setItem('alpha-finding-history',JSON.stringify(next));setError('')}}>Record disposition</Button></div>{history.filter(h=>h.findingId===f.id).map((h,i)=><p key={i}>{h.at} · {h.owner} · {h.action} · {h.note} · expiry {h.expiry??'—'} · retest {h.retest??'not supplied'} · {h.status}</p>)}</div>):<p>No saved control breach for this run. Workflow failures remain separate from control findings.</p>}{error&&<Alert severity="error">{error}</Alert>}</section>
}
