import {useState} from 'react';
import {Box,Typography,TextField,MenuItem,Chip,Button,Tabs,Tab,Tooltip,Table,TableHead,TableBody,TableRow,TableCell,TableContainer,Alert} from '@mui/material';
import {traceFor,type Span} from './traceData';
import {exportJson} from './evidenceApi';
import type {Run} from './evidence';
const colors={agent:'#4285f4',model:'#a78bfa',tool:'#34a853',evaluation:'#fbbc05',handoff:'#8ab4f8'};
export function Observability({runs,onEvidence,initialRun='alpha-002'}:{initialRun?:string;runs:Run[];onEvidence:(r:Run)=>void}){
 const [runId,setRunId]=useState(initialRun),[spanId,setSpanId]=useState('tool-3'),[filter,setFilter]=useState('all'),[tab,setTab]=useState(0);
 const run=runs.find(r=>r.id===runId)??runs[0];if(!run)return <Typography>Waiting for run data…</Typography>;
 const trace=traceFor(run.id),selected=trace.spans.find(s=>s.id===spanId)??trace.spans[0];const visible=trace.spans.filter(s=>filter==='all'||s.kind===filter);
 const modelCalls=trace.spans.filter(s=>s.kind==='model');const tokens=modelCalls.reduce((a,s)=>a+(s.tokens?.input??0)+(s.tokens?.output??0),0);
 return <Box><Box className="trace-toolbar"><TextField label="Trace run" select value={run.id} onChange={e=>setRunId(e.target.value)} sx={{minWidth:230}}>{runs.map(r=><MenuItem key={r.id} value={r.id}>{r.id} · {r.scenario}</MenuItem>)}</TextField><Typography variant="caption" sx={{fontFamily:'monospace',overflowWrap:'anywhere'}}>{trace.traceId}</Typography><Button onClick={()=>exportJson(`${trace.traceId}.json`,{sample:true,...trace})}>Export trace</Button><Button onClick={()=>onEvidence(run)}>Open control evidence →</Button></Box>
 <Alert severity="info" sx={{my:2}}>Simulated trace structure and payloads. Tool names and model variant are illustrative; no calls were made. Trace timings show execution duration, while control measurements use separate one-minute evidence windows.</Alert>
 <Box className="trace-summary">{[[`${(trace.durationMs/1000).toFixed(2)} s`,'Trace duration'],[String(trace.spans.filter(s=>s.kind==='tool').length),'Tool calls'],[String(modelCalls.length),'Model calls'],[tokens.toLocaleString(),'Illustrative trace tokens'],[String(trace.spans.filter(s=>s.status==='ERROR').length),'Execution errors']].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</Box>
 <Box className="trace-workbench"><Box className="trace-waterfall"><Box className="visual-heading"><div><Typography variant="h6">Execution waterfall</Typography><Typography variant="caption" color="text.secondary">Select a span to inspect its call and result</Typography></div><TextField select label="Span type" size="small" value={filter} onChange={e=>setFilter(e.target.value)} sx={{minWidth:120}}>{['all','agent','model','tool','handoff','evaluation'].map(k=><MenuItem key={k} value={k}>{k==='all'?'All spans':k}</MenuItem>)}</TextField></Box><div className="trace-ruler"><span>Span / operation</span><div><span>0 s</span><span>3.8 s</span><span>7.62 s</span></div></div>
 {visible.map(s=><Tooltip key={s.id} title={`${s.name} · ${s.duration} ms · ${s.status}`} placement="top"><button className={`span-row ${selected.id===s.id?'active-span':''}`} onClick={()=>{setSpanId(s.id);setTab(0)}} aria-pressed={selected.id===s.id}><span className="span-label" style={{paddingLeft:s.parent?18:0}}><i style={{background:colors[s.kind]}}/><span>{s.name}<small>{s.zone} · {s.kind} · {s.status}</small></span></span><span className="span-track"><span className="span-bar" style={{left:`${s.start/trace.durationMs*100}%`,width:`${Math.max(s.duration/trace.durationMs*100,1)}%`,background:s.status==='ERROR'?'#ea4335':colors[s.kind]}}/><span className="span-duration">{s.duration} ms</span></span></button></Tooltip>)}
 <Box className="chart-legend">{Object.entries(colors).map(([k,v])=><span key={k}><i style={{background:v}}/>{k}</span>)}</Box></Box>
 <Box className="span-inspector"><Chip label={`${selected.kind} · ${selected.status}`} size="small" color={selected.status==='OK'?'default':selected.status==='ERROR'?'error':'warning'}/><Typography variant="h6" mt={2} sx={{overflowWrap:'anywhere'}}>{selected.name}</Typography><dl className="span-facts">{Object.entries({'Span ID':selected.id,'Parent span':selected.parent??'Trace root',Zone:selected.zone,'Start offset':`${selected.start} ms`,Duration:`${selected.duration} ms`}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 <Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="fullWidth"><Tab label="Input"/><Tab label="Output"/><Tab label="Attributes"/></Tabs><Box component="pre" className="payload-view">{JSON.stringify(tab===0?selected.input:tab===1?selected.output:{sample:true,traceId:trace.traceId,runId:run.id,spanId:selected.id,kind:selected.kind,zone:selected.zone,tokens:selected.tokens??null,controlId:selected.control??null},null,2)}</Box>{selected.tokens&&<Typography variant="caption">Input {selected.tokens.input} · Output {selected.tokens.output} tokens</Typography>}
 </Box></Box>
 <Box className="evaluation-ledger"><Typography variant="h6" mb={1}>Evaluation events</Typography><Typography variant="body2" color="text.secondary" mb={2}>Execution success and control compliance are distinct: a successful tool call can still contribute to a policy breach.</Typography><TableContainer><Table size="small" aria-label="Trace evaluation events"><TableHead><TableRow>{['Evaluation','Measured','Threshold','Verdict','Response'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{trace.spans.filter(s=>s.kind==='evaluation').map(s=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell>{String((s.input as {windowLatencyMs:number|null}).windowLatencyMs??'Missing')} ms</TableCell><TableCell>±10% of 100 ms</TableCell><TableCell>{(s.output as {verdict:string}).verdict}</TableCell><TableCell>No notification delivered · simulation</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>
 </Box>
}
