import {useState} from 'react';
import {Alert,Box,Button,Chip,Typography,TextField,Tabs,Tab,Table,TableBody,TableCell,TableHead,TableRow,TableContainer,Tooltip,Stepper,Step,StepLabel} from '@mui/material';
import DownloadOutlined from '@mui/icons-material/DownloadOutlined';
import ArrowForward from '@mui/icons-material/ArrowForward';
import DescriptionOutlined from '@mui/icons-material/DescriptionOutlined';
import {controls,rules,evaluate,type Run,type Control} from './evidence';
import {controlDetails,exportJson,runStatus} from './evidenceApi';
import {Radial,RunTrend,ChartHelp} from './EvidenceCharts';
const gaps=['AWS foundation not demonstrated','Real evidence ingestion missing','ServiceNow correlation missing','Notification delivery unverified','Budget enforcement missing','Second enforcement point untested'];
export function Readiness({runs,onInspect}:{runs:Run[];onInspect:(run:Run)=>void}){
 const [demo,setDemo]=useState(()=>localStorage.getItem('alpha-demo-url')||''),[tab,setTab]=useState(0);
 const pass=runs.find(r=>runStatus(r)==='Pass'),breach=runs.find(r=>runStatus(r)==='Breach');
 const thresholds=controls.map(c=>({controlId:c,...rules[c],...controlDetails[c],date:'2026-10-04',status:'Illustrative draft; not approved'}));
 const artifacts=[{name:'Evidence bundle',description:'Run IDs, verdicts, thresholds and supporting records',state:'Sample',action:()=>exportJson('SAMPLE-evidence-bundle.json',{sample:true,packets:runs.flatMap(r=>controls.map(c=>evaluate(r,c)))})},{name:'Threshold document',description:'Scope, limits, exceptions, owner, version and date',state:'Draft',action:()=>exportJson('DRAFT-thresholds.json',{sample:true,thresholds})},{name:'Architecture sketch',description:'Execution path, evaluator and evidence flow',state:'Proposed',action:()=>exportJson('DRAFT-architecture.json',{status:'Not deployed',flow:['Register → snapshot','Agents → enforcement → evaluator','Enforcement → ledger → API → console','ServiceNow → findings and receipts']})},{name:'Gap list',description:'Known limitations and outstanding integration work',state:'Draft',action:()=>exportJson('DRAFT-gaps.json',{sample:true,gaps})}];
 return <Box className="dossier"><Box className="dossier-intro"><div><Typography variant="overline" color="primary">JUDGING BRIEF</Typography><Typography variant="h5" fontWeight={650}>One question. A traceable answer.</Typography><Typography color="text.secondary" mt={1}>Name a control and run, establish the verdict, then inspect its evidence.</Typography></div><Chip label="Foundation not yet verified" color="warning" variant="outlined"/></Box>
 <Stepper alternativeLabel activeStep={0} sx={{my:4}}>{['Foundation','Observability','Extended evidence'].map(t=><Step key={t}><StepLabel>{t}</StepLabel></Step>)}</Stepper><Typography variant="caption" color="text.secondary">Sequential judging gates. No stage is marked complete until demonstrated against the workshop environment.</Typography>
 <Tabs value={tab} onChange={(_,v)=>setTab(v)} sx={{mt:3,borderBottom:1,borderColor:'divider'}} variant="scrollable"><Tab label="Judge’s desk"/><Tab label="Architecture"/><Tab label="Gaps & demo"/></Tabs>
 {tab===0&&<><Box className="rehearsal-strip"><div><Typography variant="h6">Start the two-minute rehearsal</Typography><Typography variant="body2" color="text.secondary">Synthetic runs · use control 9 to compare a pass with a breach.</Typography></div><Box display="flex" gap={1} flexWrap="wrap">{[pass,breach].map(r=>r&&<Button key={r.id} variant="outlined" endIcon={<ArrowForward/>} onClick={()=>onInspect(r)}>{r.id} · {runStatus(r)}</Button>)}</Box></Box><TableContainer><Table aria-label="Judging artifact manifest"><TableHead><TableRow><TableCell>Artifact</TableCell><TableCell>Contents</TableCell><TableCell>Readiness</TableCell><TableCell align="right">Download</TableCell></TableRow></TableHead><TableBody>{artifacts.map(a=><TableRow key={a.name}><TableCell><Box display="flex" alignItems="center" gap={1}><DescriptionOutlined sx={{fontSize:18,color:'primary.main'}}/>{a.name}</Box></TableCell><TableCell>{a.description}</TableCell><TableCell><Chip size="small" label={a.state} variant="outlined"/></TableCell><TableCell align="right"><Tooltip title={`Download ${a.name.toLowerCase()} as JSON`}><Button aria-label={`Export ${a.name.toLowerCase()}`} onClick={a.action}><DownloadOutlined fontSize="small"/></Button></Tooltip></TableCell></TableRow>)}</TableBody></Table></TableContainer><Typography variant="caption" color="text.secondary" display="block" mt={2}>All exports are draft or sample artifacts. Real passing and breaching runs are still required.</Typography></>}
 {tab===1&&<Box py={3}><Typography variant="h6">Where decisions become evidence</Typography><Typography color="text.secondary" variant="body2" mt={1}>Proposed architecture · the control register stays outside the live path.</Typography><Box className="system-diagram"><Box className="register-node"><strong>Control register</strong><small>Versioned policy & thresholds</small></Box><div className="diagram-connector">↓ distribute snapshot before execution</div><Box className="runtime-lane"><div className="diagram-node"><strong>AWS agents</strong><small>Customer → IT → Network</small></div><span>→</span><div className="diagram-node emphasis"><strong>Enforcement point</strong><small>Ask · wait · act · record</small></div><span>⇄</span><div className="diagram-node"><strong>Evaluator</strong><small>Stateless decision</small></div></Box><div className="diagram-connector">↓ record decision, action, threshold version & trace references</div><Box className="runtime-lane"><div className="diagram-node"><strong>Evidence ledger</strong><small>Preserve records and gaps</small></div><span>→</span><div className="diagram-node"><strong>Evidence API</strong><small>Query run + control + window</small></div><span>→</span><div className="diagram-node emphasis"><strong>Judge’s console</strong><small>Verdict + inspectable records</small></div></Box><div className="diagram-connector">↕ correlate run IDs with findings and notification receipts</div><div className="diagram-node"><strong>ServiceNow</strong><small>Human approvals · findings · retests</small></div></Box><Alert severity="info">This diagram describes the intended design. AWS interfaces and the second enforcement point remain to be verified.</Alert></Box>}
 {tab===2&&<Box className="gap-demo-layout"><Box><Typography variant="h6" mb={2}>Open implementation gaps</Typography><ol className="gap-list">{gaps.map(g=><li key={g}><span>{g}</span><Chip label="Pending" size="small" variant="outlined"/></li>)}</ol></Box><Box><Typography variant="h6">Demo recording</Typography><Typography variant="body2" color="text.secondary" my={2}>Link the recording after demonstrating the required foundation. Rehearse both named runs twice.</Typography><TextField fullWidth label="Demo URL" value={demo} onChange={e=>{setDemo(e.target.value);localStorage.setItem('alpha-demo-url',e.target.value)}} helperText="Saved in this browser only."/>{/^https?:\/\//.test(demo)&&<Button href={demo} target="_blank" rel="noopener noreferrer">Open recording</Button>}</Box></Box>}
 </Box>
}
export function ControlDetails({runs}:{runs:Run[]}){const [control,setControl]=useState<Control>('9');const rule=rules[control],detail=controlDetails[control];return <Box className="control-workbench"><Box className="control-index"><Typography variant="overline" color="text.secondary">Control library</Typography>{controls.map(c=><Button key={c} fullWidth onClick={()=>setControl(c)} aria-pressed={c===control} className={c===control?'selected-control':''}><span className="control-number">{c.padStart(2,'0')}</span><span>{rules[c].name}</span></Button>)}</Box><Box className="control-definition"><Box className="visual-heading"><div><Typography variant="overline" color="primary">CONTROL {control} / {rule.version}</Typography><Typography variant="h5" fontWeight={650}>{rule.name}</Typography></div><Chip label="Draft threshold" variant="outlined" size="small"/></Box><Box className="threshold-banner"><Typography fontSize={34} fontWeight={600}>{control==='7'?'≥':'≤'} {rule.limit} <Typography component="span" fontSize={17}>{rule.unit}</Typography></Typography><div><Typography variant="body2">{rule.metric}</Typography><Typography variant="caption" color="text.secondary">Owner: {rule.owner} · 04 Oct 2026</Typography></div></Box><dl className="definition-list">{Object.entries({Scope:detail.scope,'Measurement basis':rule.basis,Exceptions:detail.exceptions,'Enforcement point':detail.location,'Required action':detail.action,Notification:detail.notification}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Box className="embedded-trend" key={control}><RunTrend runs={runs} initialControl={control} fixedRun={runs.find(r=>r.id==='alpha-002')}/></Box></Box></Box>}
export function Impact({runs}:{runs:Run[]}){const [metric,setMetric]=useState(0);const measures=[{name:'Investigation time',unit:'minutes',basis:'Median duration across matched cases, before and after using this console.',needs:'Timed case IDs, start/end timestamps, baseline cohort and sample size.'},{name:'Prevented overspend',unit:'currency',basis:'Priced token reservations rejected by the gateway, deduplicated by request ID.',needs:'Blocked requests, reserved tokens, model pricing version and currency.'},{name:'Notification delivery',unit:'%',basis:'Confirmed deliveries divided by attempted breach notifications.',needs:'Breach ID, named recipient, delivery receipt and attempted timestamp.'}];const complete=runs.filter(r=>controls.every(c=>evaluate(r,c).verdict!=='Unknown')).length;return <Box className="impact-workspace"><Box className="visual-heading"><div><Typography variant="h5" fontWeight={650}>Outcomes, backed by measurements</Typography><Typography variant="body2" color="text.secondary" mt={1}>Operational impact is separate from passing a control.</Typography></div><Chip label="Awaiting live measurements" variant="outlined"/></Box><Box className="impact-evidence"><Radial value={complete} total={runs.length} label="Samples evaluable" color="#4285f4"/><div><Typography variant="h6">Can we support the claim?</Typography><Typography variant="body2" color="text.secondary" mt={1}>{complete} of {runs.length} sample runs have measurements for all three control checks. Evaluable does not mean passing.</Typography><Typography variant="caption" color="text.secondary">This is sample evidence availability, not production impact or event-recording coverage.</Typography></div></Box><Tabs value={metric} onChange={(_,v)=>setMetric(v)} variant="scrollable">{measures.map(m=><Tab key={m.name} label={m.name}/>)}</Tabs><Box className="impact-comparison"><div><Typography variant="overline">Baseline</Typography><Typography variant="h3">—</Typography><Typography color="text.secondary">Not measured</Typography></div><ArrowForward sx={{color:'text.secondary'}}/><div><Typography variant="overline">With assurance</Typography><Typography variant="h3">—</Typography><Typography color="text.secondary">Not measured</Typography></div><div className="impact-method"><Typography variant="h6">{measures[metric].name}<ChartHelp text={`Unit: ${measures[metric].unit}. Do not infer a benefit until paired evidence is available.`}/></Typography><Typography variant="body2" mt={1}>{measures[metric].basis}</Typography><Typography variant="caption" color="text.secondary" display="block" mt={2}>Required source: {measures[metric].needs}</Typography></div></Box><Box className="empty-measurement"><span className="empty-axis"/><Typography variant="body2">No observations yet</Typography><Typography variant="caption" color="text.secondary">A comparison chart will be shown once matched measurements are received.</Typography></Box></Box>}
