export type Span={id:string;parent?:string;name:string;kind:'agent'|'model'|'tool'|'evaluation'|'handoff';zone:string;start:number;duration:number;status:'OK'|'ERROR'|'BREACH';input:unknown;output:unknown;tokens?:{input:number;output:number};control?:string};
export function traceFor(runId:string){const breach=runId==='alpha-002',gap=runId==='alpha-004';const spans:Span[]=[
{id:'agent-customer',name:'customer_agent.resolve_connectivity',kind:'agent',zone:'Customer',start:0,duration:1800,status:'OK',input:{complaint:'Intermittent connection on access circuit',customerRef:'SAMPLE-CUST-104'},output:{ticketId:'SAMPLE-INC-204',nextAgent:'it_agent'}},
{id:'model-1',parent:'agent-customer',name:'Nemotron · classify complaint',kind:'model',zone:'Customer',start:70,duration:680,status:'OK',input:{purpose:'Classify fault and extract service reference',model:'Workshop Nemotron variant — pending verification'},output:{category:'network_connectivity',serviceRef:'SAMPLE-SVC-88'},tokens:{input:180,output:70}},
{id:'tool-1',parent:'agent-customer',name:'servicenow.create_incident',kind:'tool',zone:'Customer',start:800,duration:420,status:'OK',input:{serviceRef:'SAMPLE-SVC-88',category:'network_connectivity'},output:{ticketId:'SAMPLE-INC-204',state:'new'}},
{id:'gate-a',name:'Gate A · customer → IT',kind:'handoff',zone:'Boundary A',start:1800,duration:90,status:'OK',input:{from:'customer_agent',to:'it_agent',ticketId:'SAMPLE-INC-204'},output:{decision:'allow',policyVersion:'sample-policy-v1'}},
{id:'agent-it',name:'it_agent.triage',kind:'agent',zone:'IT',start:1890,duration:2450,status:'OK',input:{ticketId:'SAMPLE-INC-204'},output:{serviceRef:'SAMPLE-SVC-88',nextAgent:'network_agent'}},
{id:'tool-2',parent:'agent-it',name:'inventory.get_service_configuration',kind:'tool',zone:'IT',start:1990,duration:540,status:'OK',input:{serviceRef:'SAMPLE-SVC-88',fields:['accessCircuit','deviceRef']},output:{deviceRef:'SAMPLE-RTR-07',interface:'Gi0/1',adminState:'up'}},
{id:'model-2',parent:'agent-it',name:'Nemotron · plan diagnostics',kind:'model',zone:'IT',start:2600,duration:1100,status:'OK',input:{task:'Choose non-mutating diagnostic tools'},output:{tools:['digital_twin.get_interface_counters']},tokens:{input:gap?80:220,output:gap?20:80}},
{id:'gate-b',name:'Gate B · IT → network',kind:'handoff',zone:'Boundary B',start:4340,duration:110,status:'OK',input:{from:'it_agent',to:'network_agent'},output:{decision:'allow',policyVersion:'sample-policy-v1'}},
{id:'agent-network',name:'network_agent.diagnose',kind:'agent',zone:'Network',start:4450,duration:3100,status:gap?'ERROR':'OK',input:{deviceRef:'SAMPLE-RTR-07'},output:gap?{error:'Telemetry response unavailable'}:{diagnosis:'Interface errors detected',action:'Recommend operator inspection'}},
{id:'tool-3',parent:'agent-network',name:'digital_twin.get_interface_counters',kind:'tool',zone:'Network',start:4540,duration:gap?2100:780,status:gap?'ERROR':'OK',input:{deviceRef:'SAMPLE-RTR-07',interface:'Gi0/1'},output:gap?{code:'DEADLINE_EXCEEDED',retryable:true}:{crcErrors:37,linkState:'up',samplePeriodSeconds:60}},
...(!gap?[{id:'model-3',parent:'agent-network',name:'Nemotron · summarize diagnosis',kind:'model' as const,zone:'Network',start:5400,duration:1300,status:'OK' as const,input:{task:'Explain findings with source references'},output:{recommendation:'Escalate for physical link inspection'},tokens:{input:breach?170:runId==='alpha-003'?120:70,output:80}}]:[]),
{id:'eval-9',name:'Control 9 · latency drift test',kind:'evaluation',zone:'Governance',start:7600,duration:20,status:breach?'BREACH':gap?'ERROR':'OK',control:'9',input:{baselineMs:100,windowLatencyMs:gap?null:breach?124:runId==='alpha-003'?106:105,limitPercent:10,thresholdVersion:'demo-v0.1'},output:{verdict:gap?'Unknown':breach?'Breach':'Pass',notification:'Not sent — UI simulation'}}
];return {traceId:`sample-trace-${runId}`,runId,durationMs:7620,source:'Illustrative execution trace; not captured from AWS',spans};}
