import {statusClass} from './controlQuery';
import {useState,useEffect} from 'react';
import {Slider} from '@mui/material';
import {category,type AssuranceRun} from './assuranceData';
import type {CloudSpan,CloudMetric} from './cloudwatchData';
const colors=['#4285f4','#a78bfa','#34a883','#e9ab38','#ef7168','#27afbd'];
export function ActivityMix({runs}:{runs:AssuranceRun[]}){const labels=['Agent','Model','Tool','Authorization','Budget','Notification'];const counts=labels.map(l=>runs.reduce((n,r)=>n+r.events.filter(e=>category(e)===l).length,0));const total=counts.reduce((a,b)=>a+b,0);return <aside className="wa-panel viz-summary"><header><h2>Activity summary</h2><span>{runs.length} filtered runs</span></header><div className="viz-summary-body"><b>{total.toLocaleString()} <small>source records</small></b>{labels.map((label,i)=><div className="viz-summary-row" key={label}><span>{label}</span><strong>{counts[i]}</strong><small>{total?Math.round(counts[i]/total*100):0}%</small><div><i style={{width:`${total?counts[i]/total*100:0}%`,background:colors[i]}}/></div></div>)}<p>Records may describe the same action.</p></div></aside>}
export function RunLollipops({runs,selected,onSelect}:{runs:AssuranceRun[];selected?:string;onSelect:(id:string)=>void}){const max=Math.max(1,...runs.map(r=>r.events.length));return <section className="wa-panel"><header><h2>Run activity comparison</h2><span>Dot height = source records · select a run</span></header><div className="viz-lollipops">{runs.map(r=><button key={r.id} aria-pressed={selected===r.id} aria-label={`${r.id}: ${r.events.length} records`} onClick={()=>onSelect(r.id)}><span className="viz-stem" style={{height:`${r.events.length/max*78}%`}}><b>{r.events.length}</b></span><small title={r.id}>{r.id}</small></button>)}</div></section>}
export function ThresholdCharts({run}:{run:AssuranceRun}){const rows=[{name:'Control 7 · Event coverage',measured:run.c7.coverage,target:run.c7Threshold.coverage_target==null?null:Number(run.c7Threshold.coverage_target),unit:'%',factor:100,version:run.c7.threshold_version,verdict:run.c7.verdict},{name:'Control 16 · Spend cap',measured:run.c16['measured.value'],target:run.c16['threshold.value'],unit:'tokens',factor:1,version:run.c16['threshold.version'],verdict:run.c16.verdict}];return <section className="wa-panel"><header><h2>Measurements & thresholds</h2><span>{run.id} · whole-run evaluations</span></header><div className="viz-bullets">{rows.map(r=>{const known=typeof r.measured==='number'&&typeof r.target==='number';const scale=known?Math.max(r.measured,r.target,0.001)*1.15:1;return <div key={r.name}><div className="viz-bullet-label"><b>{r.name}</b><span>{r.verdict??'Not assessed'} · {r.version??'Version unknown'}</span></div>{known?<><div className="viz-bullet-track"><i style={{width:`${r.measured/scale*100}%`}}/><em style={{left:`${r.target/scale*100}%`}}/></div><div className="viz-bullet-label"><span>Measured: {(r.measured*r.factor).toLocaleString()} {r.unit}</span><span>│ Threshold: {(r.target*r.factor).toLocaleString()} {r.unit}</span></div></>:<p>Measurement or threshold not recorded</p>}</div>})}</div></section>}
export function FailureChart({run}:{run:AssuranceRun}){const entries=Object.entries(run.workflow.failures.reduce<Record<string,number>>((m,f)=>{const a=f.actor??'Unknown actor';m[a]=(m[a]??0)+1;return m},{}));const max=Math.max(1,...entries.map(e=>e[1]));return <section className="wa-panel"><header><h2>Failures by agent</h2><span>Recorded workflow failures · {run.id}</span></header><div className="viz-failures">{entries.length?entries.map(([actor,count])=><div key={actor}><span>{actor}</span><div><i style={{width:`${count/max*100}%`}}/></div><b>{count}</b></div>):<p>No failures recorded in this export.</p>}</div></section>}
export function AuditMatrix({runs,onSelect}:{runs:AssuranceRun[];onSelect:(id:string)=>void}){return <section className="wa-panel"><header><h2>Evaluation coverage</h2><span>✓ Satisfied · Breach · Not assessed</span></header><div className="viz-matrix">{runs.map(r=><button key={r.id} onClick={()=>onSelect(r.id)} aria-label={`Inspect ${r.id}`}><span>{r.id}</span>{[r.c7.verdict,undefined,r.c16.verdict].map((v,i)=><span key={i} className={`wa-badge ${statusClass(v)}`}>C{[7,9,16][i]} {statusClass(v)==='good'?'✓':statusClass(v)==='bad'?'Breach':v??'Not assessed'}</span>)}</button>)}</div></section>}
export function SpanWaterfall({spans,selected,onSelect}:{spans:CloudSpan[];selected?:string;onSelect:(id:string)=>void}){if(!spans.length)return <p className="wa-empty">No spans match these filters.</p>;const start=Math.min(...spans.map(s=>Date.parse(s.startTime))),end=Math.max(...spans.map(s=>Date.parse(s.endTime))),duration=Math.max(1,end-start);return <section className="wa-panel"><header><h2>Execution waterfall</h2><span>Position = start · width = duration · select a span</span></header><div className="viz-waterfall-axis"><span>Span / agent</span><span>0 s</span><span>{(duration/1000).toFixed(2)} s elapsed</span></div><div className="viz-waterfall">{spans.map(s=><button key={s.traceId+s.spanId} aria-pressed={selected===s.spanId} onClick={()=>onSelect(s.spanId)}><span className="viz-span-name">{s.name}<small>{s.service}</small></span><span className="viz-span-track"><i style={{left:`${(Date.parse(s.startTime)-start)/duration*100}%`,width:`${Math.max(.3,(Date.parse(s.endTime)-Date.parse(s.startTime))/duration*100)}%`,background:s.status==='ERROR'?'#ef7168':s.operation==='chat'?colors[0]:s.operation==='execute_tool'?colors[2]:colors[1]}}/></span><span>{s.durationMs.toFixed(1)} ms</span></button>)}</div><footer>Nested spans overlap; their durations must not be added together.</footer></section>}
export function MetricLine({samples,metric}:{samples:CloudMetric[];metric:string}){const points=[...samples].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));if(!points.length)return <p className="wa-empty">No samples for this metric.</p>;const start=Date.parse(points[0].time),end=Date.parse(points.at(-1)!.time);const max=Math.max(0,...points.map(p=>p.measurements[metric])),min=Math.min(0,...points.map(p=>p.measurements[metric]));const xy=points.map(p=>({x:45+(Date.parse(p.time)-start)/Math.max(1,end-start)*900,y:165-(p.measurements[metric]-min)/Math.max(1e-12,max-min)*140,p}));return <div className="viz-line"><svg viewBox="0 0 980 200" role="img" aria-label={`${metric}, ${points.length} samples; minimum ${Math.min(...points.map(p=>p.measurements[metric]))}, maximum ${max}. Exact values in table below.`}>{[0,.5,1].map(t=><g key={t}><line x1="45" x2="945" y1={165-t*140} y2={165-t*140} stroke="var(--border)"/><text x="38" y={169-t*140} textAnchor="end">{(min+(max-min)*t).toPrecision(3)}</text></g>)}<polyline points={xy.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="var(--primary)" strokeWidth="2"/>{xy.map(({x,y,p},i)=><circle key={i} cx={x} cy={y} r="3" fill="var(--primary)"><title>{p.time}: {p.measurements[metric]}</title></circle>)}</svg></div>}

export function RunTimeline({runs,selected,onSelect,onWindowIds}:{runs:AssuranceRun[];selected?:string;onSelect:(id:string)=>void;onWindowIds?:(ids:string[])=>void}){
 const [window,setWindow]=useState([0,100]),[clusters,setClusters]=useState(true);
 const entries=runs.map(r=>{const times=r.events.map(e=>e.time?Date.parse(e.time):NaN).filter(Number.isFinite);return {r,time:times.length?Math.min(...times):NaN}}).filter(e=>Number.isFinite(e.time)).sort((a,b)=>a.time-b.time);

 const start=entries[0]?.time??0,end=entries.at(-1)?.time??1,span=Math.max(1,end-start),lo=start+span*window[0]/100,hi=start+span*window[1]/100,width=Math.max(1,hi-lo);
 const visible=entries.filter(e=>e.time>=lo&&e.time<=hi),buckets=Array.from({length:100},()=>0);entries.forEach(e=>buckets[Math.min(99,Math.floor((e.time-start)/span*100))]+=e.r.events.length);const peak=Math.max(1,...buckets);
 const visibleKey=visible.map(e=>e.r.id).join('|');useEffect(()=>{onWindowIds?.(visibleKey?visibleKey.split('|'):[])},[visibleKey,onWindowIds]);
 const groups=clusters?Array.from({length:12},(_,i)=>visible.filter(e=>Math.min(11,Math.floor((e.time-lo)/width*12))===i)).filter(g=>g.length):visible.map(e=>[e]);
 const label=(t:number)=>new Date(t).toLocaleString('en-GB',{timeZone:'UTC',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}),time=(t:number)=>new Date(t).toLocaleTimeString('en-GB',{timeZone:'UTC',hour:'2-digit',minute:'2-digit'});
 const chosen=visible.find(e=>e.r.id===selected),zoom=(percent:number)=>{const center=chosen?(chosen.time-start)/span*100:(window[0]+window[1])/2;const a=Math.max(0,Math.min(100-percent,center-percent/2));setWindow([a,a+percent])};
 return <section className="wa-panel ref-clusters"><header><h2><span className="ref-icon">▥</span> Run timeline</h2><span>▦ {label(lo)} – {label(hi)} UTC</span></header><div className="ref-tools"><span>Zoom</span><div className="ref-zoom">{[['Full range',100],['6h',Math.min(100,21600000/span*100)],['3h',Math.min(100,10800000/span*100)],['1h',Math.min(100,3600000/span*100)]].map(([text,n])=><button key={text} aria-pressed={Math.abs(window[1]-window[0]-Number(n))<.01} onClick={()=>zoom(Number(n))}>{text}</button>)}</div><label><input type="checkbox" checked={clusters} onChange={e=>setClusters(e.target.checked)}/> Show clusters</label><span>{visible.length} runs in view</span></div><div className="ref-overview"><div className="viz-mini">{buckets.map((n,i)=><i key={i} style={{height:`${n/peak*100}%`}}/>)}</div><div className="ref-brush" style={{left:`${window[0]}%`,width:`${window[1]-window[0]}%`}}/><Slider value={window} min={0} max={100} step={.1} disableSwap getAriaLabel={i=>i?'Window end':'Window start'} getAriaValueText={v=>label(start+span*v/100)+' UTC'} onChange={(_,v)=>{const a=v as number[];if(a[1]-a[0]>=.5)setWindow(a)}}/></div><div className="viz-time-axis">{[0,.25,.5,.75,1].map(t=><span key={t}>{label(start+span*t)}</span>)}</div><div className="ref-periods">{Array.from({length:6},(_,i)=><div key={i}><b>{time(lo+width*i/6)}</b><span>{new Date(lo+width*i/6).toLocaleDateString('en-GB',{timeZone:'UTC',day:'numeric',month:'short'})}</span></div>)}</div><div className="ref-cluster-plot">{chosen&&<div className="ref-cursor" style={{left:`${3+(chosen.time-lo)/width*94}%`}}><span>{time(chosen.time)} UTC</span></div>}{groups.map((g,i)=>{const timestamp=g.reduce((n,e)=>n+e.time,0)/g.length,active=g.some(e=>e.r.id===selected),count=g.reduce((n,e)=>n+e.r.events.length,0);return <button key={g.map(e=>e.r.id).join()} className={`ref-cluster ${g.length>1?'group':''} ${active?'active':''}`} style={{left:`${3+(timestamp-lo)/width*94}%`}} aria-pressed={active} aria-label={`${label(timestamp)} UTC, ${g.length} runs, ${count} source records. Select ${g[0].r.id}`} title={g.map(e=>e.r.id).join(', ')} onClick={()=>{onSelect(g[0].r.id);if(g.length>1){const a=(Math.min(...g.map(e=>e.time))-start)/span*100,b=(Math.max(...g.map(e=>e.time))-start)/span*100;setWindow([Math.max(0,a-1),Math.min(100,b+1)])}}}><span>{clusters?<><b>{count}</b><small>records</small></>:<b>{count}</b>}</span></button>})}</div><div className="viz-time-axis">{[0,.25,.5,.75,1].map(t=><span key={t}>{time(lo+width*t)}</span>)}</div><footer>Run records / Grouped runs · select a cluster to zoom <span style={{marginLeft:'auto'}}>Counts = source records · {runs.length-entries.length} runs without timestamps</span></footer></section>
}
