import {useEffect,useMemo,useState} from 'react';
import {Alert,Button,MenuItem,TextField} from '@mui/material';
import {type AssuranceData,categories,category,failed} from './assuranceData';
import {recordsOf,filterWorkspace,relatedRecords,actorMetrics,coverageRows} from './workspaceModel';
import {EvidenceIndex,NotificationSummary} from './ScreenSummaries';
import {RecordDrawer} from './RecordDrawer';
import {exportJson} from './evidenceApi';
const display=(v:any)=>v==null?'Not recorded':typeof v==='object'?JSON.stringify(v):String(v);
export function WorkspaceExplorer({data,mode,onRun}:{data:AssuranceData;mode:'events'|'agents'|'coverage'|'notifications';onRun:(id:string)=>void}){
 const [search,setSearch]=useState(''),[actor,setActor]=useState(''),[kind,setKind]=useState(mode==='notifications'?'Notification':''),[run,setRun]=useState(''),[onlyFailures,setFailures]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[selected,setSelected]=useState(''),[page,setPage]=useState(0);
 const records=useMemo(()=>recordsOf(data),[data]);const actors=useMemo(()=>actorMetrics(records),[records]);
 const invalid=(from&&!Number.isFinite(Date.parse(from+'Z')))||(to&&!Number.isFinite(Date.parse(to+'Z')))||(from&&to&&from>to);
 const filtered=invalid?[]:filterWorkspace(records,{search,actor,kind,run,failures:onlyFailures,from,to});const visible=filtered;const event=records.find(e=>e.key===selected);const related=event?relatedRecords(event,records):[];
 useEffect(()=>{setPage(0)},[search,actor,kind,run,onlyFailures,from,to]);
 const clear=()=>{setSearch('');setActor('');setKind(mode==='notifications'?'Notification':'');setRun('');setFailures(false);setFrom('');setTo('');setPage(0)};
 if(mode==='coverage')return <><section className="wa-panel"><header><h2>Evidence coverage by run</h2><span>Field presence · source records, not independent validation</span><Button onClick={()=>exportJson('alpha-evidence-coverage.json',{readAt:data.readAt,coverage:coverageRows(data.runs)})}>Export coverage</Button></header><div className="wa-table-wrap"><table><thead><tr>{['Run','Records','Timestamp','Trace ID','Authority / policy','Threshold version','Notifications','Delivery status'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{coverageRows(data.runs).map(r=><tr key={r.run}><td><button className="wa-link" onClick={()=>onRun(r.run)}>{r.run}</button></td>{[r.records,r.timed,r.traced,r.authority,r.limits,r.notifications,r.receipts].map((v,i)=><td key={i}>{v}{i>0&&i<5?` / ${r.records}`:''}</td>)}</tr>)}</tbody></table></div><footer>A delivery status alone does not verify the recipient, finding or external receipt. Duplicate records remain counted.</footer></section><section className="wa-panel"><header><h2>Collection errors</h2><span>{data.errors.length} source errors</span></header><div className="wa-evidence-body">{data.errors.length?<pre>{JSON.stringify(data.errors,null,2)}</pre>:<p>No collection errors reported in this snapshot.</p>}<p>{data.freshness}</p></div></section></>;
 return <><div className="wa-toolbar"><TextField label="Search all evidence" value={search} onChange={e=>setSearch(e.target.value)}/><TextField select label="Agent / principal" value={actor} onChange={e=>setActor(e.target.value)}><MenuItem value="">All actors</MenuItem>{actors.map(a=><MenuItem value={a.actor} key={a.actor}>{a.actor}</MenuItem>)}</TextField>{mode!=='notifications'&&<TextField select label="Record category" value={kind} onChange={e=>setKind(e.target.value)}><MenuItem value="">All categories</MenuItem>{categories.map(c=><MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField>}<TextField select label="Run scope" value={run} onChange={e=>setRun(e.target.value)}><MenuItem value="">All runs</MenuItem>{data.runs.map(r=><MenuItem key={r.id} value={r.id}>{r.id}</MenuItem>)}</TextField><Button variant={onlyFailures?'contained':'outlined'} onClick={()=>setFailures(!onlyFailures)}>Failures & refusals</Button><Button onClick={clear}>Clear all</Button></div><div className="wa-toolbar"><TextField label="From · UTC" type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField label="To · UTC" type="datetime-local" value={to} onChange={e=>setTo(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><span>{visible.length.toLocaleString()} records · {new Set(visible.map(e=>e.runId)).size} runs</span><Button onClick={()=>exportJson('alpha-window-evidence.json',{source:data.source,readAt:data.readAt,query:{search,actor,kind,run,onlyFailures,fromUTC:from,toUTC:to},records:visible})}>Export selected window</Button></div>{invalid&&<Alert severity="error">Enter a valid UTC window with the start before the end.</Alert>}
 {mode==='notifications'&&<Alert severity="info">These are recorded notification events. External delivery is established only with a matching finding, recipient and provider receipt; a local delivered status alone is insufficient.</Alert>}{mode==='agents'&&<section className="wa-panel"><header><h2>Agent & principal inventory</h2><span>Observed in collected evidence · select an actor to inspect</span></header><div className="wa-table-wrap"><table><thead><tr>{['Actor','Runs','Source records','Model records','Tool records','Failures / refusals','Traces','p95 recorded duration'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{actorMetrics(visible).map(a=><tr key={a.actor}><td><button className="wa-link" onClick={()=>setActor(a.actor)}>{a.actor}</button></td>{[a.runs,a.records,a.models,a.tools,a.failures,a.traces,a.p95==null?'Not recorded':`${a.p95.toFixed(0)} ms`].map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><footer>Duration is end minus recorded start, across available records. It is not a quality-drift result or complete distributed trace latency.</footer></section>}
 {mode==='events'&&<EvidenceIndex records={invalid?[]:filterWorkspace(records,{search,actor,kind:'',run,failures:onlyFailures,from,to})} onCategory={setKind}/>}{mode==='notifications'&&<NotificationSummary records={visible}/>}

 <div className="wa-records-layout"><section className="wa-panel"><header><h2>{mode==='notifications'?'Notification ledger':mode==='agents'?'Actor evidence':'Evidence records'}</h2><span>{visible.length.toLocaleString()} records</span></header><div className="wa-table-wrap wa-event-list"><table><thead><tr><th>Time · UTC</th><th>Category / action</th><th>{mode==='notifications'?'Recipient / run':'Actor / run'}</th><th>{mode==='notifications'?'Delivery status':'Outcome'}</th></tr></thead><tbody>{visible.slice(page*40,(page+1)*40).map(e=><tr key={e.key} className={event?.key===e.key?'selected':''}><td>{e.time?.replace('T',' ').replace('Z','')??'Not recorded'}</td><td><button className="wa-link" onClick={()=>setSelected(e.key)}>{category(e)} · {e.phase??'Transport'}</button></td><td>{(mode==='notifications'?e.recipient:e.actor)??'Not recorded'}<small>{e.runId}</small></td><td><span className={failed(e)?'wa-badge bad':''}>{display(mode==='notifications'?e.delivery_status:e.verdict??e.outcome??e.decision)}</span></td></tr>)}</tbody></table>{!visible.length&&<p className="wa-empty">No records match this scope.</p>}</div><footer><Button disabled={!page} onClick={()=>setPage(page-1)}>Previous</Button><span>{visible.length?`${page*40+1}–${Math.min(visible.length,(page+1)*40)}`:'0'} of {visible.length}</span><Button disabled={(page+1)*40>=visible.length} onClick={()=>setPage(page+1)}>Next</Button></footer></section><RecordDrawer event={event} related={related} onClose={()=>setSelected('')} onSelect={setSelected} onRun={id=>{setSelected('');onRun(id)}}/></div></>;
}
