import {useEffect,useState} from 'react';
import {Alert,Box,Button,Chip,MenuItem,TextField,Typography} from '@mui/material';
import {parseWorkshop,workshopLinks,type WorkshopSnapshot} from './workshopEvidence';
import {exportJson} from './evidenceApi';
export function WorkshopTrustChain(){
 const [data,setData]=useState<WorkshopSnapshot|null>(null),[error,setError]=useState(''),[id,setId]=useState(''),[selected,setSelected]=useState(''),[tab,setTab]=useState<'decisions'|'gateway'>('decisions'),[loading,setLoading]=useState(false);
 async function refresh(){setLoading(true);try{const response=await fetch('/data/workshop-evidence.json',{cache:'no-store'});if(!response.ok)throw new Error('Workshop snapshot unavailable');setData(parseWorkshop(await response.json()));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load evidence')}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 const run=data?.runs.find(r=>r.id===id)??data?.runs[0];const events=run?.events??[];const event=events.find(e=>e.event_id===selected)??events[0];const refs=run?.report['evidence.refs']??[];
 return <section className="trust-v2" aria-label="Workshop trust chain"><div className="tc-runbar"><Chip size="small" label="AWS evidence snapshot"/><span className="tc-source">{data?`Captured ${new Date(data.capturedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST`:'Loading source…'}</span><Button disabled={loading} onClick={refresh}>Reload snapshot</Button><Button component="label">Import export<input hidden type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];try{if(!file)return;if(file.size>2000000)throw new Error('Export must be under 2 MB');setData(parseWorkshop(JSON.parse(await file.text())));setId('');setSelected('');setError('')}catch(err){setError(err instanceof Error?err.message:'Invalid export')}finally{e.target.value=''}}}/></Button><Button component="a" href={workshopLinks.ide} target="_blank" rel="noopener noreferrer">Open AWS IDE ↗</Button><Button component="a" href={workshopLinks.servicenow} target="_blank" rel="noopener noreferrer">ServiceNow ↗</Button></div>
 {error&&<Alert severity="error" sx={{mb:2}}>{error}{data?' · Previous snapshot retained.':''}</Alert>}
 {run&&data&&<><div className="tc-runbar"><TextField select label="Workshop run" value={run.id} onChange={e=>{setId(e.target.value);setSelected('')}} sx={{minWidth:270,maxWidth:'100%'}}>{data.runs.map(r=><MenuItem key={r.id} value={r.id}>{r.scenario} · {r.id.slice(-8)}</MenuItem>)}</TextField><div className="tc-runmeta"><strong>{run.id}</strong><span>Run manifest: {run.completed?'completed':'completion not established'}</span></div><Button onClick={()=>exportJson(`${run.id}-workshop-evidence.json`,{...data,runs:[run]})}>Export evidence</Button></div>
 <div className="tc-assurance"><div><small>07 · Event recording</small><strong>Not assessed for this run</strong></div><div><small>09 · Performance drift</small><strong>Not assessed for this run</strong></div><div><small>16 · Spend cap</small><strong>{run.report.verdict??'No verdict in export'}</strong></div><div><small>Evidence coverage</small><strong>{refs.length} gateway references</strong><small>Completeness {run.budget.reserved?'unresolved':'not independently verified'}</small></div></div>
 <div className="tc-workspace"><div className="tc-execution"><div className="tc-sectionbar"><div><h2>Recorded decisions</h2><p>Actual timestamps and actor labels from the workshop</p></div><div className="tc-toggle" role="group" aria-label="Evidence source"><button aria-pressed={tab==='decisions'} onClick={()=>setTab('decisions')}>Decisions</button><button aria-pressed={tab==='gateway'} onClick={()=>setTab('gateway')}>Gateway usage</button></div></div>
 {tab==='decisions'?<div className="tc-list ws-records">{events.map(e=><button key={e.event_id} aria-pressed={event?.event_id===e.event_id} className={event?.event_id===e.event_id?'selected':''} onClick={()=>setSelected(e.event_id)}><time>{e.emitted_at.slice(11,19)} UTC</time><span>{e.actor}<br/>{e.phase}</span><span>{e.verdict??e.delivery_status??'Recorded'}</span></button>)}</div>:<div className="ws-records"><p className="tc-proof-note">Independent gateway references. Agent-to-call attribution is not verified; no synthetic joins are added.</p>{refs.length?refs.map(f=><div className="ws-gateway" key={f.call_id}><code>{f.call_id}</code><span>{f.at} · {f.input_tokens+f.output_tokens} tokens</span></div>):<Alert severity="warning">No gateway references in this evaluator export.</Alert>}</div>}
 <div className="tc-budget"><div><h3>Shared budget</h3><span>{run.budget.committed.toLocaleString()} committed · {run.budget.reserved.toLocaleString()} reserved</span></div><div className="tc-meter" role="img" aria-label={`${run.budget.committed} committed; ${run.budget.reserved} reserved; cap ${run.budget.threshold.cap}`}><i style={{width:`${Math.min(100,run.budget.committed/run.budget.threshold.cap*100)}%`}}/><b style={{width:`${Math.min(100,run.budget.reserved/run.budget.threshold.cap*100)}%`}}/></div><div className="tc-budget-labels"><span>Alert {run.budget.threshold.alert.toLocaleString()}</span><span>Refusal {run.budget.threshold.refusal.toLocaleString()}</span><span>Cap {run.budget.threshold.cap.toLocaleString()}</span></div></div>
 {(run.report.warnings??[]).map(w=><p className="tc-proof-note" key={w}>Evidence limitation: {w}</p>)}{run.budget.reserved>0&&<Alert severity="warning" sx={{mt:2}}>Outstanding reservations: {run.budget.reserved.toLocaleString()} tokens. Usage is not fully reconciled.</Alert>}
 </div><aside className="tc-proof" aria-label="Workshop action proof"><small>ACTION PROOF</small><h2>{event?.phase??'No event selected'}</h2><dl>{Object.entries({'Actor':event?.actor??'Unknown','Time (UTC)':event?.emitted_at??'Unknown','Policy':run.budget.threshold.version,'Decision':event?.verdict??'Not recorded on this event','Reason':event?.reason??'Not recorded','Call ID':event?.call_id??'Not recorded','Gateway match':'Not verified per call','Recipient':event?.recipient??'Not recorded on this event','Delivery':event?.delivery_status??'No receipt on this event','Owner':run.budget.threshold.owner}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><details><summary>Source record</summary><pre>{JSON.stringify(event,null,2)}</pre></details><p className="tc-proof-note">{run.sourcePath}<br/>Unsigned imported evidence. Reload reads the saved export; it does not query AWS.</p></aside></div>
 <div className="tc-next"><div><strong>Continue in ServiceNow</strong><p>Browser access verified. Matching this run to a ServiceNow record remains unverified. Opening the workspace does not create an incident or deliver a notification.</p></div><Button component="a" href={workshopLinks.servicenow} target="_blank" rel="noopener noreferrer">Open Control Tower ↗</Button></div></>}
 </section>
}
export function WorkshopConnections(){return <Box><Typography variant="h6">Workshop connections</Typography><Box className="tc-next"><div><strong>AWS Workshop Studio</strong><p>Real run exports loaded in Trust chain. Snapshot import; no continuous AWS connection.</p></div><Button component="a" href={workshopLinks.workshop} target="_blank" rel="noopener noreferrer">Open workshop ↗</Button></Box><Box className="tc-next"><div><strong>ServiceNow · browser workflow</strong><p>Authenticated browser access confirmed during this review. AI connections shows 56 schedules, including successful TMF discovery jobs. Team-account and run correlation are not yet verified.</p></div><Button component="a" href={workshopLinks.servicenow} target="_blank" rel="noopener noreferrer">Open connections ↗</Button></Box><Box className="tc-next"><div><strong>AI Agent Studio</strong><p>Manage workflows in ServiceNow using your existing browser session.</p></div><Button component="a" href={workshopLinks.studio} target="_blank" rel="noopener noreferrer">Open Agent Studio ↗</Button></Box><Alert severity="info" sx={{mt:3}}>No ServiceNow API is used. Browser access, discovery success and per-run evidence are separate verification steps.</Alert></Box>}
